### ISSUE TITLE
Add support for passing the mapping Class to Json Types

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hibernate-types#133]
Currently, the mapping Type is resolved by scanning the annotated entity attribute. However, if we want to execute a query like this one:

```
JsonNode ratings = (JsonNode) entityManager
.createNativeQuery(
	"SELECT " +
	"  JSON_QUERY(properties, '$.reviews') AS ratings " +
	"FROM book " +
	"WHERE " +
	"  JSON_VALUE(properties, '$.title') = :title", Tuple.class)
.setParameter("title", "High-Performance Java Persistence")
.unwrap(NativeQuery.class)
.addScalar("ratings", JsonStringType.INSTANCE)        
.getSingleResult();
```

We will get a `NullPointerException` as the Java descriptor will not be able to resolve the expected mapping `Class`:

```
java.lang.NullPointerException
	at java.lang.Class.isAssignableFrom(Native Method)
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.fromString(JsonTypeDescriptor.java:104)
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.wrap(JsonTypeDescriptor.java:165)
	at com.vladmihalcea.hibernate.type.json.internal.AbstractJsonSqlTypeDescriptor$1.doExtract(AbstractJsonSqlTypeDescriptor.java:34)
```

**Comment by vladmihalcea** [comment]
Fixed.
