### ISSUE TITLE
Serialization problem when using JsonNodeBinaryType and Hibernate 2nd-level cache

### ISSUE THREAD

**Issue by andyflury** [vladmihalcea/hibernate-types#14]
Hi Vlad

Congrats to you project! I found your suggestions very helpful!

One small issue I noticed, when using the JsonNodeBinaryType. When I turn on Hibernate 2nd level cache through the following two properties:

`
hibernate.cache.use_second_level_cache=true
hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.EhCacheRegionFactory
`

Then I get the following exception:
`
java.lang.ClassCastException: com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to java.io.Serializable
	at org.hibernate.type.descriptor.java.MutableMutabilityPlan.disassemble(MutableMutabilityPlan.java:41)
	at org.hibernate.type.AbstractStandardBasicType.disassemble(AbstractStandardBasicType.java:326)
	at org.hibernate.type.TypeHelper.disassemble(TypeHelper.java:145)
	at org.hibernate.cache.spi.entry.StandardCacheEntryImpl.<init>(StandardCacheEntryImpl.java:74)
	at org.hibernate.persister.entity.AbstractEntityPersister$StandardCacheEntryHelper.buildCacheEntry(AbstractEntityPersister.java:5246)
	at org.hibernate.persister.entity.AbstractEntityPersister.buildCacheEntry(AbstractEntityPersister.java:4331)
	at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:201)
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:144)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1115)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:973)
	at org.hibernate.loader.Loader.doQuery(Loader.java:921)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355)
	at org.hibernate.loader.Loader.doList(Loader.java:2554)
	at org.hibernate.loader.Loader.doList(Loader.java:2540)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)
	at org.hibernate.loader.Loader.list(Loader.java:2365)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:497)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:387)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:236)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1300)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
`

Any idea how to get around this?
Thanks

**Comment by vladmihalcea** [comment]
Thanks.

Can you fork the repository and provide a test case for it. You can override the `properties` method to provide the 2nd-level cache properties.

I think we need to override the `assemble` and `disassemble` methods in the `JsonNodeBinaryType`. Try to transform the `JsonNode` to a `String` instead of serializing it, and , for deserialization, make it a `JsonNode` from the `String` object.

Send me a Pull Request with it and thanks for contributing.

**Comment by andyflury** [comment]
Thanks Vlad
Yes, I will provide a test case. 
I looked at overwriting assemble and disassemble, problem is that those methods are final.
Regards
Andy

**Comment by vladmihalcea** [comment]
@andyflury A test case is a good start I'll investigate to see what we can do about it.

**Comment by vladmihalcea** [comment]
Fixed by [this commit](https://github.com/vladmihalcea/hibernate-types/commit/4331315b8f534930a2f4e6916ba7da90906f6c9a).
