### ISSUE TITLE
NPE thrown by AbstractArrayTypeDescriptor#setParameterValues when creating a PostgreSQL ARRAY

### ISSUE THREAD

**Issue by jones-gareth** [vladmihalcea/hibernate-types#142]
This is an issue I had with a Postgres array and the fix I'm using.

I have a Hibernate (5.3)/Spring boot project and a repository query that returns a Postgres string array:
```
@Query(
      nativeQuery = true,
      value = "select s.id, s.smiles, s.fingerprint, array_agg(i.identifier) identities from structure s join configuration_tag t on (t.structure_id = s.id) join identity i on (i.configuration_tag_id = t.id) where t.configuration_tag = ? group by s.id order by s.id asc"
)
  Slice<StructureAndIdentities> findConfigurationTagsAndStructure(
      String configurationTag, Pageable pageable);
```

using your hibernate types to handle the returned array.

```
<dependency>
            <groupId>com.vladmihalcea</groupId>
            <artifactId>hibernate-types-52</artifactId>
            <version>2.7.1</version>
        </dependency>
```

I get a nullpointerexception:

```
Caused by: java.lang.NullPointerException
	at com.vladmihalcea.hibernate.type.array.internal.AbstractArrayTypeDescriptor.setParameterValues(AbstractArrayTypeDescriptor.java:34)
	at com.vladmihalcea.hibernate.type.array.StringArrayType.setParameterValues(StringArrayType.java:50)
	at org.hibernate.type.TypeFactory.injectParameters(TypeFactory.java:106)
	at org.hibernate.type.TypeFactory.type(TypeFactory.java:92)
```
in
```
public void setParameterValues(Properties parameters) {
        this.arrayObjectClass = ((ParameterType)parameters.get("org.hibernate.type.ParameterType")).getReturnedClass();
    }
```
The issue is that parameters is empty-, it is set empty in org.hibernate.type.TypeFactory#injectParameters prior to calling setParameterValues.  Perhaps this is a new change for 5.3.
```
public static void injectParameters(Object type, Properties parameters) {
        if (ParameterizedType.class.isInstance(type)) {
            if (parameters == null) {
                ((ParameterizedType)type).setParameterValues(EMPTY_PROPERTIES);
```

Tweaking your code from https://vladmihalcea.com/how-to-map-java-and-sql-arrays-with-jpa-and-hibernate this simple fix solved the issue:
```
@Override
    public void setParameterValues(Properties parameters) {
    if (parameters.containsKey(PARAMETER_TYPE)) {
          arrayObjectClass = ((ParameterType) parameters.get(PARAMETER_TYPE)).getReturnedClass();
        }
    }
```

Since `arrayObjectClass` is already set to a String array this works file for my purposes.

Thanks for your excellent work on the Hibernate types library- without it I don't think I'd have got this working in Hibernate!

**Comment by vladmihalcea** [comment]
Thanks for the investigation. Would you mind sending a Pull Request as well?

**Comment by vladmihalcea** [comment]
Applied upstream, thanks
