### ISSUE TITLE
Issue with jackson-databind version 2.9.0

### ISSUE THREAD

**Issue by 4rpit** [vladmihalcea/hibernate-types#16]
Hi,

I have dependencies of jackson-databind with version 2.9.0 in my project and I am getting an exception  with stacktrace
com.vladmihalcea.hibernate.type.json.internal.AbstractJsonSqlTypeDescriptor$1.doExtract(AbstractJsonSqlTypeDescriptor.java:34)
        at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
        at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:238)
        at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:234)
        at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:224)
        at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:300)
        at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:2727)
        at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1729)
        at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1655)
        at org.hibernate.loader.Loader.getRow(Loader.java:1544)
        at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:727)
        at org.hibernate.loader.Loader.processResultSet(Loader.java:972)
        at org.hibernate.loader.Loader.doQuery(Loader.java:930)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
        at org.hibernate.loader.Loader.doList(Loader.java:2617)
        at org.hibernate.loader.Loader.doList(Loader.java:2600)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2429)
        at org.hibernate.loader.Loader.list(Loader.java:2424)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:501)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:371)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1326)
        at org.hibernate.internal.QueryImpl.list(QueryImpl.java:87)
        at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:606)
        at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:483)

Thanks,
Arpit

**Comment by vladmihalcea** [comment]
Just [tested it](https://github.com/vladmihalcea/hibernate-types/commit/ac3a5ac8fe74f6b69f221656eb3cbc3233548997) and 5.2 works fine with Jackson 2.9.0. 

You'll have to debug it and see why it fails for you. It's something else.
