### ISSUE TITLE
Empty multi-dimensional arrays throw ClassCastException

### ISSUE THREAD

**Issue by MakarovAlexey** [vladmihalcea/hibernate-types#161]
Hello! I have mapped field 'textByLang' with type String[][]. I use PostgreSQL. When I try load field with two-dimensional array '{{abc,xyz}}' all working fine, but when I load empty array ('{}'), I receive the following error:

```
Caused by: org.hibernate.PropertyAccessException: Could not set field value [[Ljava.lang.String;@e4f480d] value by reflection : [class ru.ritos.lang.LangText.textByLang] setter of ru.ritos.lang.LangText.textByLang
	at org.hibernate.property.access.spi.SetterFieldImpl.set(SetterFieldImpl.java:61)
	at org.hibernate.tuple.component.AbstractComponentTuplizer.setPropertyValues(AbstractComponentTuplizer.java:76)
	at org.hibernate.tuple.component.PojoComponentTuplizer.setPropertyValues(PojoComponentTuplizer.java:99)
	at org.hibernate.type.ComponentType.setPropertyValues(ComponentType.java:450)
	at org.hibernate.type.ComponentType.resolve(ComponentType.java:697)
	at org.hibernate.type.Type.resolve(Type.java:487)
	at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:226)
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:160)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1179)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:1028)
	at org.hibernate.loader.Loader.doQuery(Loader.java:964)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
	at org.hibernate.loader.Loader.doList(Loader.java:2815)
	at org.hibernate.loader.Loader.doList(Loader.java:2797)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2629)
	at org.hibernate.loader.Loader.list(Loader.java:2624)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:396)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1396)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1558)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1526)
	... 55 more
Caused by: java.lang.IllegalArgumentException: Can not set [[Ljava.lang.String; field ru.ritos.lang.LangText.textByLang to [Ljava.lang.String;
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.hibernate.property.access.spi.SetterFieldImpl.set(SetterFieldImpl.java:41)
	... 76 more
```

**Comment by vladmihalcea** [comment]
According to the error:

    Can not set [[Ljava.lang.String; field ru.ritos.lang.LangText.textByLang to [Ljava.lang.String;

It looks like you are trying to save your own custom `LangText` Java type into a `String[]`.

The ARRAY type allows you to save a Java array into a PostgreSQL array. More, every issue should be accompanied by a replicating test case that proves the issue, so I'm going to close this one until you provide the replicating test case as a Pull Request.

**Comment by MakarovAlexey** [comment]
Here test case and classes
#162

**Comment by vladmihalcea** [comment]
Thanks. I'll review it when I have some time.

**Comment by vladmihalcea** [comment]
Fixed.
