### ISSUE TITLE
When fetching an entity from the second-level cache, ListArrayType throws UnsupportedOperationException

### ISSUE THREAD

**Issue by marceloverdijk** [vladmihalcea/hibernate-types#169]
Having a entity like:

```
@Entity
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
@TypeDefs({
        @TypeDef(name = "list-array", typeClass = ListArrayType.class)
})
public class Project {

    @Column(name = "previous_names")
    @Type(type = "list-array")
    private List<String> previousNames;

    ..
```

the first time the `Project` is queried everything is fine.
The second time - when the object is retrieved from the Hibernate second-level cache - an `UnsupportedOperationException` is thrown unfortunately.

```
java.lang.UnsupportedOperationException: The provided [Ljava.lang.Object;@17b59449 is not a List!
        at com.vladmihalcea.hibernate.type.array.internal.ListArrayTypeDescriptor$1.deepCopyNotNull(ListArrayTypeDescriptor.java:27) ~[hibernate-types-52-2.9.1.jar:na]
        at org.hibernate.type.descriptor.java.MutableMutabilityPlan.deepCopy(MutableMutabilityPlan.java:35) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
        at org.hibernate.type.descriptor.java.MutableMutabilityPlan.assemble(MutableMutabilityPlan.java:30) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
        at org.hibernate.type.AbstractStandardBasicType.assemble(AbstractStandardBasicType.java:319) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
        at org.hibernate.type.TypeHelper.assemble(TypeHelper.java:101) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
        at org.hibernate.cache.spi.entry.StandardCacheEntryImpl.assemble(StandardCacheEntryImpl.java:135) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
        at org.hibernate.loader.entity.CacheEntityLoaderHelper.convertCacheEntryToEntity(CacheEntityLoaderHelper.java:311) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
        at org.hibernate.loader.entity.CacheEntityLoaderHelper.processCachedEntry(CacheEntityLoaderHelper.java:177) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
        at org.hibernate.loader.entity.CacheEntityLoaderHelper.loadFromSecondLevelCache(CacheEntityLoaderHelper.java:150) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
```

**Comment by vladmihalcea** [comment]
This issue will require a replicating test case. I'll be rather busy in the following weeks, so if you can supply a fix via a Pull Request, then maybe I could issue a minor release sooner than late February or March.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by marceloverdijk** [comment]
Verified in `2.9.3-SNAPSHOT` it works now 👍

**Comment by vladmihalcea** [comment]
Thanks for the confirmation.
