### ISSUE TITLE
A NullPointerException is thrown when adding a ListArrayType definition to a MappedSuperClass

### ISSUE THREAD

**Issue by tfeiner** [vladmihalcea/hibernate-types#189]
Hello,

if I try to use

```
@TypeDef(
		name = "list-array",
		typeClass = ListArrayType.class
)
```
and

```
	@Type(type = "list-array")
	@Column(name = "myList", columnDefinition = "text[]")
	private List<String> myList;
```

in a MappedSuperClass then this error is thrown:

```
Caused by: org.hibernate.MappingException: Could not instantiate Type: com.vladmihalcea.hibernate.type.array.ListArrayType
	at org.hibernate.type.TypeFactory.type(TypeFactory.java:96)
	at org.hibernate.type.TypeFactory.byClass(TypeFactory.java:66)
	at org.hibernate.type.TypeResolver.heuristicType(TypeResolver.java:126)
	at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:473)
	at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:455)
	at org.hibernate.mapping.Property.isValid(Property.java:227)
	at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:624)
	at org.hibernate.mapping.RootClass.validate(RootClass.java:267)
	at org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:343)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:461)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1237)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:391)
	... 106 more
Caused by: java.lang.NullPointerException
	at com.vladmihalcea.hibernate.type.util.ReflectionUtils.getMemberGenericTypeOrNull(ReflectionUtils.java:552)
	at com.vladmihalcea.hibernate.type.array.internal.ListArrayTypeDescriptor.setParameterValues(ListArrayTypeDescriptor.java:82)
	at com.vladmihalcea.hibernate.type.array.internal.AbstractArrayType.setParameterValues(AbstractArrayType.java:42)
	at org.hibernate.type.TypeFactory.injectParameters(TypeFactory.java:109)
	at org.hibernate.type.TypeFactory.type(TypeFactory.java:92)
	... 119 more
```

**Comment by vladmihalcea** [comment]
Every issue needs to have a replicating test case. Without a replicating test case to prove it, there is no issue. I'll keep the issue open for a while so that you can provide the test case. If no test case is provided, I'm going to close it.

**Comment by tfeiner** [comment]
Hello,

thank you for your quick answer.

You can find a test case here: https://github.com/tfeiner/hibernate-types-test

Just execute cc.feiner.MyEntityTest

Thank you in advance,

kind regards,

Thomas Feiner

**Comment by vladmihalcea** [comment]
Fixed.
