### ISSUE TITLE
Add support for "empty" String values when mapping PostgreSQL range column types

### ISSUE THREAD

**Issue by flozano** [vladmihalcea/hibernate-types#209]
I was trying to fix this myself but I don't see any obvious way that doesn't involve allowing some kind of empty `Range` in the range class.

Basically, postgres supports ranges of type `[4,4)` but transform them to `empty` [1]:
```
-- includes no points (and will be normalized to 'empty')
SELECT '[4,4)'::int4range;
```

So when such value is parsed by Range, you get an exception.
```
java.lang.IllegalArgumentException: Cannot find comma character
	at com.vladmihalcea.hibernate.type.range.Range.ofString(Range.java:250)
	at com.vladmihalcea.hibernate.type.range.Range.longRange(Range.java:334)
	at com.vladmihalcea.hibernate.type.range.PostgreSQLRangeType.get(PostgreSQLRangeType.java:65)
	at com.vladmihalcea.hibernate.type.range.PostgreSQLRangeType.get(PostgreSQLRangeType.java:37)
	at com.vladmihalcea.hibernate.type.ImmutableType.nullSafeGet(ImmutableType.java:98)
	at com.vladmihalcea.hibernate.type.ImmutableType.hydrate(ImmutableType.java:290)
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:3068)
	at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1866)
	at org.hibernate.loader.Loader.hydrateEntityState(Loader.java:1794)
	at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1767)
	at org.hibernate.loader.Loader.getRow(Loader.java:1615)
	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:745)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:1008)
	at org.hibernate.loader.Loader.doQuery(Loader.java:964)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
	at org.hibernate.loader.Loader.doList(Loader.java:2838)
	at org.hibernate.loader.Loader.doList(Loader.java:2820)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2652)
	at org.hibernate.loader.Loader.list(Loader.java:2647)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:396)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1404)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1562)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1530)
	at org.hibernate.query.Query.getResultList(Query.java:165)

```

[1] https://www.postgresql.org/docs/9.3/rangetypes.html

**Comment by vladmihalcea** [comment]
Maybe it's because PostgreSQL returns `empty` instead of `[4,4)`. 

This is what you need to do:

1. You need to create a replicating test case in the [`PostgreSQLRangeTypeTest`](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-52/src/test/java/com/vladmihalcea/hibernate/type/range/PostgreSQLRangeTypeTest.java)
2. You need to add support for parsing the `empty` String value and return an empty `Range` Java object instance.

After you are done, send me the Pull Request so I can review it.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by flozano** [comment]
oh, thanks a lot. I planned to try this weekend, you were faster...

**Comment by icorne** [comment]
Hello,

I'm getting a same issue with com.vladmihalcea.hibernate.type.range.PostgreSQLRangeType and the zone missing.
![image](https://user-images.githubusercontent.com/3259342/234818928-d170e6fd-f05d-4f3f-b559-105edb1f9da3.png)

In what version was this fixed?

**Comment by flozano** [comment]
2.9.8 in theory:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/1159291/234819482-7e16a5ef-64c8-4f14-b8e1-6a8da8e2ee23.png">

**Comment by icorne** [comment]
I see, I'm sorry, we were running the latest of the old package! Thanks :)

**Comment by icorne** [comment]
It seems the zonedDateTimeRange is not supporting empty yet

![image](https://user-images.githubusercontent.com/3259342/234824501-4a3e9930-2815-4745-b047-f415bd36a645.png)
results in anullpointer

**Comment by flozano** [comment]
maybe better to open a separate issue, this is different than the one I reported.
