### ISSUE TITLE
Should Hibernate Types handle this polymorphism example?

### ISSUE THREAD

**Issue by warwickdufour** [vladmihalcea/hibernate-types#235]
I'd like to find out if Hibernate Types is designed to handle this situation which is currently failing for me. I have class hierarchy as follows:

### Hierarchy Root:
```java
@TypeDefs({ @TypeDef(name = "json", typeClass = JsonStringType.class),
		@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class),
		@TypeDef(name = "jsonb-node", typeClass = JsonNodeBinaryType.class), })
@MappedSuperclass
public abstract class BaseEntity implements Serializable {
...
}
```

### Intermediate subclass:
```java
@MappedSuperclass
public abstract class BaseReport extends BaseEntity {
...
}
```
### Main Abstract class (note class member 'payload')
```java
@XmlRootElement
@Entity
@DynamicUpdate
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "OPREP_TYPE")
@Table(name = "OPMET_REP")
@AttributeOverrides({ @AttributeOverride(name = "uuid", column = @Column(name = "OPREP_UUID")),
		@AttributeOverride(name = "version", column = @Column(name = "OPREP_VERSION")),
		@AttributeOverride(name = "createDateTime", column = @Column(name = "OPREP_CREATED")),
		@AttributeOverride(name = "updateDateTime", column = @Column(name = "OPREP_UPDATED")),
		@AttributeOverride(name = "rawText", column = @Column(name = "OPREP_RAWTEXT", length = 8000)) })
public abstract class OpmetReport<T extends OpmetPayload> extends BaseReport {
...
	@Type(type = "jsonb")
	@Column(name = "OPREP_PAYLOAD", columnDefinition = "jsonb")
	// @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include =
	// JsonTypeInfo.As.PROPERTY, property = "@class")
	private T payload;
...
}
```

### Subclassed by both:
```java
@Entity
@DiscriminatorValue("METAR")
public class TacMetarReport extends OpmetReport<TacMetarPayload> {
...
}
```
and
```java
@Entity
@DiscriminatorValue("TAF")
public class TacTafReport extends OpmetReport<TacTafPayload> {
...
}
```
### Note that TacMetarPayload and TacTafPayload both inherit from:
```java
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
@JsonSubTypes({ @JsonSubTypes.Type(value = TacMetarPayload.class), @JsonSubTypes.Type(value = TacSpeciPayload.class),
		@JsonSubTypes.Type(value = TacTafPayload.class) })
public abstract class OpmetPayload {
...
}
```
### Symptoms
Hibernate Types is being used in a Quarkus environment. Persistence works fine but an exception is thrown when fetching a TacTafReport<TacTafPayload> instance:

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'aero.avitech.met.opmet.store.entity.TacMetarPayload' as a subtype of 'aero.avitech.met.opmet.store.entity.TacTafPayload': Not a subtype
 at [Source: (String)"{"type": "METAR", "cavok": true, "@class": "aero.avitech.met.opmet.store.entity.TacMetarPayload", "clouds": null, "weather": null, "dewPoint": "10", "location": "EDDL", "pressure": "Q1010", "seaState": null, "forecasts": [{"cavok": null, "cloud": null, "weather": null, "visibility": null, "surfaceWind": null, "changePeriod": null, "changeIndicator": "NOSIG"}], "windShear": null, "visibility": null, "runwayState": null, "surfaceWind": "15010KT", "recentWeather": null, "airTemperature": "17", "sea"[truncated 109 chars]; line: 1, column: 44]
        at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
        at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1761)
        at com.fasterxml.jackson.databind.DatabindContext._throwNotASubtype(DatabindContext.java:280)
        at com.fasterxml.jackson.databind.DatabindContext.resolveAndValidateSubType(DatabindContext.java:241)
        at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:72)
        at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:66)
        at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:156)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1178)
        at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3214)
        at com.vladmihalcea.hibernate.type.util.ObjectMapperWrapper.fromString(ObjectMapperWrapper.java:50)
        ... 98 more
```

Fetching a TacTafReport<TacTafPayload> instance works fine. In fact it appears as though the OpmetPayload sub-type of the first fetched instance is cached by Jackson and used for all subsequent deserializations.

**Comment by vladmihalcea** [comment]
From the exception message, it looks like inheritance is, indeed, supported. Otherwise, you wouldn't get that exception.

If you can manage to replicate it using a test case in this repository, then I'll take a look at it.

**Comment by warwickdufour** [comment]
Apologies for not being clearer. I realise that inheritance is supported , I was just wondering if the particular use case my code demonstrated was. Having cloned the repository I have reproduced the error in a JUnit test that is modelled on your PostgreSQLJsonParameterizedPropertyTest and I give it below together with the error I'm getting:

```java
package com.vladmihalcea.hibernate.type.json;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.vladmihalcea.hibernate.type.util.AbstractPostgreSQLIntegrationTest;
import java.net.URL;
import net.ttddyy.dsproxy.QueryCount;
import net.ttddyy.dsproxy.QueryCountHolder;
import org.hibernate.Session;
import org.hibernate.annotations.NaturalId;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.junit.Test;

import javax.persistence.*;
import org.hibernate.annotations.DynamicUpdate;

import static org.junit.Assert.*;

/**
 * @author Warwick Dufour
 */
public class PostgreSQLJsonParameterizedPropertyTest2 extends AbstractPostgreSQLIntegrationTest {

    @Override
    protected Class<?>[] entities() {
        return new Class<?>[]{
            Hardback.class,
            Paperback.class
        };
    }

    @Override
    protected void afterInit() {
        System.out.println("afterInit():");
        doInJPA(entityManager -> {
            HardbackDescription hardbackDescription = new HardbackDescription();
            hardbackDescription.setTitle("High-Performance Java Persistence");
            hardbackDescription.setAuthor("Vlad Mihalcea");
            hardbackDescription.setPublisher("Amazon");
            hardbackDescription.setPrice(44.99);
            hardbackDescription.setFlysheetQuality("High/Glossy");
            entityManager.persist(
                new Hardback()
                    .setIsbn("978-9730228236")
                    .setDescription(hardbackDescription)
            );
            
            PaperbackDescription paperbackDescription = new PaperbackDescription();
            paperbackDescription.setTitle("High-Performance Java Persistence - 2nd Edition");
            paperbackDescription.setAuthor("Vlad Mihalcea");
            paperbackDescription.setPublisher("Amazon");
            paperbackDescription.setPrice(12.99);
            paperbackDescription.setCoverSticker("Booker Prize Winner 2020");
            entityManager.persist(
                new Paperback()
                    .setIsbn("978-9730228237")
                    .setDescription(paperbackDescription)
            );
        });
    }
    
    @Test
    public void testFindAndDeserialize() {
        doInJPA(entityManager -> {
            QueryCountHolder.clear();
            Hardback hardback = entityManager.unwrap(Session.class)
                .bySimpleNaturalId(Hardback.class)
                .load("978-9730228236");
            assertEquals("High/Glossy", hardback.getDescription().getFlysheetQuality());
            
            Paperback paperback = entityManager.unwrap(Session.class)
                .bySimpleNaturalId(Paperback.class)
                .load("978-9730228237");
            assertEquals("Booker Prize Winner 2020", paperback.getDescription().getCoverSticker());
        });
        
        QueryCount queryCount = QueryCountHolder.getGrandTotal();
        assertEquals(2, queryCount.getTotal());
    }


    @TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
    @Entity(name="AbstractBook")
    @DynamicUpdate
    @Inheritance(strategy = InheritanceType.SINGLE_TABLE)
    @DiscriminatorColumn(name = "BOOK_TYPE")
    @Table(name = "BOOKS")
    public static class AbstractBook<T extends BookDescription> {

        @Id
        @GeneratedValue
        private Long id;
        
        @NaturalId
        protected String isbn;

        @Type(type = "jsonb")
        @Column(columnDefinition = "jsonb")
        private T description;

        public String getIsbn() {
            return isbn;
        }

        public AbstractBook<T> setIsbn(String isbn) {
            this.isbn = isbn;
            return this;
        }

        public T getDescription() {
            return description;
        }

        public AbstractBook setDescription(T d) {
            this.description = d;
            return this;
        }
    }

    @Entity(name = "Hardback")
    @DiscriminatorValue("HARDBACK")
    public static class Hardback extends AbstractBook<HardbackDescription> {
    }

    @Entity(name = "Paperback")
    @DiscriminatorValue("PAPERBACK")
    public static class Paperback extends AbstractBook<PaperbackDescription> {
    }
    
    @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
    @JsonSubTypes({
        @JsonSubTypes.Type(value = HardbackDescription.class),
        @JsonSubTypes.Type(value = PaperbackDescription.class)
    })
    public abstract static class BookDescription {

        private String title;
        private String author;
        private String publisher;
        private double price;
        private URL url;

        public String getTitle() {
            return title;
        }

        public BookDescription setTitle(String title) {
            this.title = title;
            return this;
        }

        public String getAuthor() {
            return author;
        }

        public BookDescription setAuthor(String author) {
            this.author = author;
            return this;
        }

        public String getPublisher() {
            return publisher;
        }

        public BookDescription setPublisher(String publisher) {
            this.publisher = publisher;
            return this;
        }

        public double getPrice() {
            return price;
        }

        public BookDescription setPrice(double price) {
            this.price = price;
            return this;
        }

        public URL getUrl() {
            return url;
        }

        public BookDescription setUrl(URL u) {
            this.url = u;
            return this;
        }
        
    }
    
    public static class HardbackDescription extends BookDescription {

        private String flysheetQuality;

        public String getFlysheetQuality() {
            return flysheetQuality;
        }

        public HardbackDescription setFlysheetQuality(String s) {
            this.flysheetQuality = s;
            return this;
        }
        
    }
    
    public static class PaperbackDescription extends BookDescription {

        private String coverSticker;

        public String getCoverSticker() {
            return coverSticker;
        }

        public PaperbackDescription setCoverSticker(String s) {
            this.coverSticker = s;
            return this;
        }
    }
}
```

the error output I'm getting is:

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.938 s <<< FAILURE! - in com.vladmihalcea.hibernate.type.json.PostgreSQLJsonParameterizedPropertyTest2
[ERROR] testFindAndDeserialize(com.vladmihalcea.hibernate.type.json.PostgreSQLJsonParameterizedPropertyTest2)  Time elapsed: 1.911 s  <<< ERROR!
java.lang.IllegalArgumentException: The given string value: {"url": null, "price": 12.99, "title": "High-Performance Java Persistence - 2nd Edition", "@class": "com.vladmihalcea.hibernate.type.json.PostgreSQLJsonParameterizedPropertyTest2$PaperbackDescription", "author": "Vlad Mihalcea", "publisher": "Amazon", "coverSticker": "Booker Prize Winner 2020"} cannot be transformed to Json object
	at com.vladmihalcea.hibernate.type.json.PostgreSQLJsonParameterizedPropertyTest2.lambda$testFindAndDeserialize$1(PostgreSQLJsonParameterizedPropertyTest2.java:74)
	at com.vladmihalcea.hibernate.type.json.PostgreSQLJsonParameterizedPropertyTest2.testFindAndDeserialize(PostgreSQLJsonParameterizedPropertyTest2.java:65)
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: 
Could not resolve type id 'com.vladmihalcea.hibernate.type.json.PostgreSQLJsonParameterizedPropertyTest2$PaperbackDescription' as a subtype of [simple type, class com.vladmihalcea.hibernate.type.json.PostgreSQLJsonParameterizedPropertyTest2$HardbackDescription]: Not a subtype
 at [Source: (String)"{"url": null, "price": 12.99, "title": "High-Performance Java Persistence - 2nd Edition", "@class": "com.vladmihalcea.hibernate.type.json.PostgreSQLJsonParameterizedPropertyTest2$PaperbackDescription", "author": "Vlad Mihalcea", "publisher": "Amazon", "coverSticker": "Booker Prize Winner 2020"}"; line: 1, column: 101]
	at com.vladmihalcea.hibernate.type.json.PostgreSQLJsonParameterizedPropertyTest2.lambda$testFindAndDeserialize$1(PostgreSQLJsonParameterizedPropertyTest2.java:74)
	at com.vladmihalcea.hibernate.type.json.PostgreSQLJsonParameterizedPropertyTest2.testFindAndDeserialize(PostgreSQLJsonParameterizedPropertyTest2.java:65)
```

It should be possible for you to just create this class as a sibling of PostgreSQLJsonParameterizedPropertyTest and reproduce the problem if you are interested in it.

Regards,

Warwick

**Comment by vladmihalcea** [comment]
Now that you have a replicating test case, just try to figure out what the issue it and provide a replicating test case with a proposed fix. I'll review it after you provide it.

**Comment by warwickdufour** [comment]
So, the problem appears to be in Hibernate's TypeResolver or at least my understanding and use of Hibernate, not Hibernate Types as Hibernate is passing it the wrong subclass. With the time available to me I have had to work around the problem using a project specific @Parameter argument to Hibernate's @Type annotation. In summary I do not have a fix to propose.

**Comment by vladmihalcea** [comment]
Thanks for your report. If the problem is in Hibernate, it's a good idea to create a Hibernate Jira issue and reference this issue for more details.

**Comment by imasood90** [comment]
HI @warwickdufour. I am facing the same issue. What have you provided in the 'parameter' in @type annotation? Can you specify in any example?

**Comment by egemenozkan** [comment]
Hello @vladmihalcea @warwickdufour @imasood90 ,
I'm facing same issue as well, do you have any solution on your side? 

Reference point.
https://vladmihalcea.com/polymorphic-json-objects-hibernate/
