### ISSUE TITLE
Support Java 9+ Java Collections Immutable Types

### ISSUE THREAD

**Issue by austinarbor** [vladmihalcea/hibernate-types#236]
Consider the class
```java
@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
class Test {
   @Type(name = "jsonb")
   @Column
   private List<Map<String,String>> m;

   // getters, setters, etc...
}
```

If you have a entity
```java
Test t = new Test();
t.setM(List.of(new HashMap<>());
```

This does not properly serialize and throws the exception 
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.util.ImmutableCollections$List12` (no Creators, like default construct, exist): no default no-arguments constructor found
```
```
Caused by: java.lang.IllegalArgumentException: The given byte array cannot be transformed to Json object
	at com.vladmihalcea.hibernate.type.util.ObjectMapperWrapper.fromBytes(ObjectMapperWrapper.java:68)
	at com.vladmihalcea.hibernate.type.util.ObjectMapperJsonSerializer.clone(ObjectMapperJsonSerializer.java:27)
	at com.vladmihalcea.hibernate.type.util.ObjectMapperWrapper.clone(ObjectMapperWrapper.java:97
```

  
If instead you use
```java
t.setM(Collections.singletonList(new HashMap<>()));
```
This works fine

Jackson itself supports deserializing from the List/Map static constructors so it should work here also

**Comment by vladmihalcea** [comment]
First, you should provide a replicating test case.

Afterward, you should debug the Hibernate Types code and think of a way to address this issue. Once you have a proper solution, send me a Pull Request, and I'll review it.

**Comment by vladmihalcea** [comment]
Closed as I couldn't replicate it.
