### ISSUE TITLE
Allow JSON Types to handle parameterized entity attribute type variables

### ISSUE THREAD

**Issue by charllie** [vladmihalcea/hibernate-types#237]
Related to my last pull request https://github.com/vladmihalcea/hibernate-types/pull/225

The unit test you added is working fine. I got a use case where it throws an exception (https://github.com/charllie/hibernate-types-52-spring-boot).

I tried to transpose my use case into a unit test many times but I can't make it fail. Here's the stack trace:

```
sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3333) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3279) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_144]
```

Thanks again for your time 👍

**Comment by vladmihalcea** [comment]
If it cannot be replicated in this repository, then the issue might be caused by other frameworks in your Spring Boot application.

**Comment by charllie** [comment]
Thanks for your reply. My last pull request solved the issue but I don't know if it breaks some other tests or not.

**Comment by vladmihalcea** [comment]
Fixed.
