### ISSUE TITLE
A ClassNotFoundException is thrown when using an Enum List or Array in Kotlin

### ISSUE THREAD

**Issue by wafisher** [vladmihalcea/hibernate-types#238]
Following [your directions](https://vladmihalcea.com/postgresql-array-java-list/), I tried to implement an enum list in Kotlin using:

```
    @Type(
        type = "com.vladmihalcea.hibernate.type.array.ListArrayType",
        parameters = [Parameter(name = SQL_ARRAY_TYPE, value = "door_state")]
    )
    lateinit var doorsOpen: List<DoorState>
```

and

```
CREATE TYPE door_state AS ENUM (
    'OPEN', 'CLOSED'
    );

CREATE TABLE realtime.loadweigh
(
    [...other columns...]
    doors_open door_state[]
);
```

this produced the following stacktrace:

```
...

Caused by: org.hibernate.MappingException: Could not instantiate Type: com.vladmihalcea.hibernate.type.array.ListArrayType
	at org.hibernate.type.TypeFactory.type(TypeFactory.java:96)
	at org.hibernate.type.TypeFactory.byClass(TypeFactory.java:66)
	at org.hibernate.type.TypeResolver.heuristicType(TypeResolver.java:126)
	at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:473)
	at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:455)
	at org.hibernate.mapping.Property.isValid(Property.java:227)
	at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:624)
	at org.hibernate.mapping.RootClass.validate(RootClass.java:267)
	at org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:343)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:461)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1237)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:391)
	... 84 more
Caused by: java.lang.IllegalArgumentException: java.lang.ClassNotFoundException: ? extends org.lirr.backend.model.domain.DoorState
	at com.vladmihalcea.hibernate.type.util.ReflectionUtils.handleException(ReflectionUtils.java:612)
	at com.vladmihalcea.hibernate.type.util.ReflectionUtils.getClass(ReflectionUtils.java:467)
	at com.vladmihalcea.hibernate.type.array.internal.ListArrayTypeDescriptor.setParameterValues(ListArrayTypeDescriptor.java:103)
	at com.vladmihalcea.hibernate.type.array.internal.AbstractArrayType.setParameterValues(AbstractArrayType.java:42)
	at org.hibernate.type.TypeFactory.injectParameters(TypeFactory.java:109)
	at org.hibernate.type.TypeFactory.type(TypeFactory.java:92)
	... 97 more
Caused by: java.lang.ClassNotFoundException: ? extends org.lirr.backend.model.domain.DoorState
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.vladmihalcea.hibernate.type.util.ReflectionUtils.getClass(ReflectionUtils.java:465)
	... 101 more
```

I believe this has to do with the definition of a Kotlin `List` type:

```
public interface List<out E> : Collection<E>
```

such that line 103 of your `ReflectionUtils` file gets a wildcard type instead of a specific class.

I have a workaround right now using a proper `java.util.ArrayList` but figured I'd highlight this.

**Comment by vladmihalcea** [comment]
The project is only tested with Java. If you provide a fix that works with both Java and Kotlin, I'll investigate it.

**Comment by wafisher** [comment]
Just modified it slightly. The following works for me:

```
ParameterizedType parameterizedType = (ParameterizedType) memberGenericType;
Type genericType = parameterizedType.getActualTypeArguments()[0];
if (genericType instanceof WildcardType) {
    // Account for kotlin.collections.List: the type we want is actually the upper bound
    genericType = ((WildcardType) genericType).getUpperBounds()[0];
}
Class arrayElementClass = ReflectionUtils.getClass(genericType.getTypeName());
```

**Comment by vladmihalcea** [comment]
Can you send me a Pull Request with this fix? Thanks.

**Comment by vladmihalcea** [comment]
Fixed.
