### ISSUE TITLE
string value: {"routingKey": "aaaa"} cannot be transformed to Json object

### ISSUE THREAD

**Issue by favccxx** [vladmihalcea/hibernate-types#256]
I try to  save java object to json value in postgres as jsonb format, it works fine. But when try to query it, it failed. and told me string value cannot be transformed to Json object.

I have see all the issues, but i think you did not solve the problem. such as #  #88， 

https://vladmihalcea.com/the-hibernate-types-open-source-project-is-born/
In this article, if you just declare String object, and stored as jsonb, i think it will not work good for program. 

@Type(type = "jsonb")
@Column(columnDefinition = "jsonb")
private JavaObject fromRoute;

> org.springframework.dao.InvalidDataAccessApiUsageException: The given string value: {"routingKey": "aaaa", "routeServer": "RabbitServer", "exchangeName": "abcd"} cannot be transformed to Json object; nested exception is java.lang.IllegalArgumentException: The given string value: {"routingKey": "aaaa", "routeServer": "RabbitServer", "exchangeName": "abcd"} cannot be transformed to Json object
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:374) ~[spring-orm-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:257) ~[spring-orm-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528) ~[spring-orm-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149) ~[spring-data-jpa-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at com.sun.proxy.$Proxy149.findByStatus(Unknown Source) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at com.sun.proxy.$Proxy100.findByStatus(Unknown Source) ~[na:na]

**Comment by vladmihalcea** [comment]
You need to provide a replicating test case so that I can also see the problem. Fork the repository and use any of the existing tests to create a new one that can show the problem. I'll take a look at it when you send the Pull Request with the test case.

**Comment by favccxx** [comment]
I found the problem, when we save the simple Java Object as json, it works fine. But when i use the basic or parent Java class, it will return wrong for json parse error. 
When we use spring data mongo, it uses the _class properties to solve the problem. Below is the case.

class BaseModel(){
...
}

class BizModel extends baseModel(){
...
}

class JsonbClass(){
  @Type(type = "jsonb")
  @Column(columnDefinition = "jsonb")
  BaseModel  baseModel;
}

when we save JsonbClass, we could use BizModel to store, but when we try to get data.  BizModel String value could not transfer to BaseModel json.

**Comment by vladmihalcea** [comment]
Send me a Pull Request with the replicating test case, and I'll check it afterward. Without a test case, there's no issue.
