### ISSUE TITLE
Persist Java list causes Postgres SQL syntax exception / Spring Boot Data

### ISSUE THREAD

**Issue by lunanigra** [vladmihalcea/hibernate-types#273]
Thanks for your cool library!

I have a use-case quite similar to your example...
https://vladmihalcea.com/how-to-map-json-collections-using-jpa-and-hibernate

It is Postgres and a Java list containing a simple object of two string fields. But instead of using Hibernate directly I'm using Spring Boot Data JPA Repository.

When trying to persist the object an exception is thrown (Postgres SQL system error). I logged the SQL statement; but don't see the issue.

Reading objects from database works perfectly - so, guess the setup is not wrong at all. It also working when using a Java list containing just strings and not a simple object.

Any idea? Data type in Postgres is JSONB. Should it work using Spring JPA Repository?
I'm also using Lombok. But even removing all Lombok annoations from the list class; same error.

**Comment by vladmihalcea** [comment]
Spring Boot JPA uses Hibernate, so it should work.

Yoh said about some error, but you forgot to add it.

**Comment by lunanigra** [comment]
Unluckily the error messag is not really verbose. This is what I see in the logs...

**Hibernate statement**
```
Hibernate: 
    update
        db_name.table_name
    set
        code=?,
        date_time_local=?,
        date_time_utc=?,
        area_code=?,
        ...
        references=?,
        ...
    where
        id=?
```

**Mapped values**
```
2020-10-07 09:42:26.206 TRACE 4800 --- [nio-8888-exec-8] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [VARCHAR] - [IFUB#]
2020-10-07 09:42:26.206 TRACE 4800 --- [nio-8888-exec-8] o.h.type.descriptor.sql.BasicBinder      : binding parameter [2] as [TIMESTAMP] - [2019-06-17T19:21+02:00]
2020-10-07 09:42:26.206 TRACE 4800 --- [nio-8888-exec-8] o.h.type.descriptor.sql.BasicBinder      : binding parameter [3] as [TIMESTAMP] - [2019-06-17 17:21:00.0]
2020-10-07 09:42:26.206 TRACE 4800 --- [nio-8888-exec-8] o.h.type.descriptor.sql.BasicBinder      : binding parameter [4] as [VARCHAR] - [ASW]
...
2020-10-07 09:42:26.210 TRACE 4800 --- [nio-8888-exec-8] o.h.type.descriptor.sql.BasicBinder      : binding parameter [88] as [OTHER] - [[Reference(type=BK, number=0ANR005081), Reference(type=LI, number=0ANR005081-001)]]
...
2020-10-07 09:42:26.224 TRACE 4800 --- [nio-8888-exec-8] o.h.type.descriptor.sql.BasicBinder      : binding parameter [109] as [BIGINT] - [38334]
2020-10-07 09:42:26.247  WARN 4800 --- [nio-8888-exec-8] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 42601
2020-10-07 09:42:26.247 ERROR 4800 --- [nio-8888-exec-8] o.h.engine.jdbc.spi.SqlExceptionHelper   : FEHLER: Syntaxfehler bei ?references?
```

**Original exception**
```
org.postgresql.util.PSQLException: FEHLER: Syntaxfehler bei ?references?
  Position: 2460
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505) ~[postgresql-42.2.9.jar:42.2.9]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241) ~[postgresql-42.2.9.jar:42.2.9]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310) ~[postgresql-42.2.9.jar:42.2.9]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447) ~[postgresql-42.2.9.jar:42.2.9]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368) ~[postgresql-42.2.9.jar:42.2.9]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158) ~[postgresql-42.2.9.jar:42.2.9]
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124) ~[postgresql-42.2.9.jar:42.2.9]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar:na]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3450) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3312) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3726) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:201) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:1.8.0_202]
```

**Database value** (DB to Java works perfectly)
```
[{"type": "BK", "number": "9IST007772"}, {"type": "LI", "number": "9IST007772-002"}]
```

**Reference class**
```
package com.db.jpa;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Reference implements Serializable {

    private String type;

    private String number;
}
```

**Comment by vladmihalcea** [comment]
I don't understand the exception message as it's not in English and there's no other info provided.

I'll need several hours of consulting to investigate it and provide you a solution. If your company interested in my services, let me know.

**Comment by lunanigra** [comment]
Ok, if you say that it should  work at least on paper I will provide a simple stand-alone application and run some more tests.
I will also try to switch the message to English - German error code are a pain.

**Comment by vladmihalcea** [comment]
I don't know if it should work as it involves Lombok. A replicating test case would help, but due to my busy schedule, I don't think I could investigate it until January or February.

**Comment by lunanigra** [comment]
Sorry to say so... But got it!

"references" seems to be a reserved word in Postgres. Funny that you can use it via UI and on select statements; not on update statememts.

Done now.

**Comment by vladmihalcea** [comment]
Great. I'm glad you found the solution. Probably that's what that German error message was telling, right?

**Comment by lunanigra** [comment]
Not really ;)

Even in English the error message is not totally clear - all statements are generated and you don't see a concrete mistake.

```
2020-10-07 13:47:32.973 CEST [11872] ERROR:  syntax error at or near "references" at character 2460
2020-10-07 13:47:32.973 CEST [11872] STATEMENT:  update db_name.table_name set activity_code=$1, activity_date_time_local=$2, references=$88 where id=$109
```

But when putting the query into a GUI with highlighting it became clearer... Thanks again for your cool lib!

**Comment by vladmihalcea** [comment]
That's the classic syntax failure exception message. You get this whenever the SQL Parser cannot parse the SQL query either because you are using a non-supported keyword or a non-existing table identifier.
