### ISSUE TITLE
Dependency conflict org.hibernate.common:hibernate-commons-annotations 

### ISSUE THREAD

**Issue by JensPiegsa** [vladmihalcea/hibernate-types#279]
I run into a dependency conflict trying to deploy my application using hibernate-types-52 version **2.10.0** to WildFly **21.0.0.Final**.

It looks like this is caused by WildFly being shipped with hibernate-commons-annotations **5.0.5.Final** but hibernate-types-52 2.10.0 depending on **5.0.4.Final**.

Are there any known incompatibilities / workarounds?

The stack trace:
```
14:10:37,041 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 81) MSC000001: Failed to start service jboss.persistenceunit."OpenIssues.war#openIssuesPU": org.jboss.msc.service.StartException in service jboss.persistenceunit."OpenIssues.war#openIssuesPU": javax.persistence.PersistenceException: [PersistenceUnit: openIssuesPU] Unable to build Hibernate SessionFactory
        at org.jboss.as.jpa@21.0.0.Final//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:198)
        at org.jboss.as.jpa@21.0.0.Final//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:128)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.wildfly.security.elytron-private@1.13.1.Final//org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:659)
        at org.jboss.as.jpa@21.0.0.Final//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:213)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: openIssuesPU] Unable to build Hibernate SessionFactory
        at org.hibernate@5.3.18.Final//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:1327)
        at org.hibernate@5.3.18.Final//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1253)
        at org.hibernate.jipijapa-hibernate5-3@21.0.0.Final//org.jboss.as.jpa.hibernate5.TwoPhaseBootstrapImpl.build(TwoPhaseBootstrapImpl.java:44)
        at org.jboss.as.jpa@21.0.0.Final//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:170)
        ... 10 more
Caused by: org.hibernate.MappingException: Could not instantiate Type: com.vladmihalcea.hibernate.type.json.JsonBinaryType
        at org.hibernate@5.3.18.Final//org.hibernate.type.TypeFactory.type(TypeFactory.java:96)
        at org.hibernate@5.3.18.Final//org.hibernate.type.TypeFactory.byClass(TypeFactory.java:66)
        at org.hibernate@5.3.18.Final//org.hibernate.type.TypeResolver.heuristicType(TypeResolver.java:126)
        at org.hibernate@5.3.18.Final//org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:471)
        at org.hibernate@5.3.18.Final//org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:453)
        at org.hibernate@5.3.18.Final//org.hibernate.mapping.Property.isValid(Property.java:227)
        at org.hibernate@5.3.18.Final//org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:624)
        at org.hibernate@5.3.18.Final//org.hibernate.mapping.RootClass.validate(RootClass.java:267)
        at org.hibernate@5.3.18.Final//org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:347)
        at org.hibernate@5.3.18.Final//org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:466)
        at org.hibernate@5.3.18.Final//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1250)
        ... 12 more
Caused by: java.lang.ClassCastException: class org.hibernate.annotations.common.reflection.java.JavaXProperty cannot be cast to class org.hibernate.annotations.common.reflection.XProperty (org.hibernate.annotations.common.reflection.java.JavaXProperty is in unnamed module of loader 'org.hibernate.commons-annotations@5.0.5.Final' @46016aa4; org.hibernate.annotations.common.reflection.XProperty is in unnamed module of loader 'deployment.OpenIssues.war' @6fd30c58)
        at deployment.OpenIssues.war//com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.setParameterValues(JsonTypeDescriptor.java:65)
        at deployment.OpenIssues.war//com.vladmihalcea.hibernate.type.json.JsonBinaryType.setParameterValues(JsonBinaryType.java:84)
        at org.hibernate@5.3.18.Final//org.hibernate.type.TypeFactory.injectParameters(TypeFactory.java:109)
        at org.hibernate@5.3.18.Final//org.hibernate.type.TypeFactory.type(TypeFactory.java:92)
        ... 22 more
```

**Comment by vladmihalcea** [comment]
The hibernate-types-52 artifact should use the minimum dependency supported by Hibernate 5.2. If I upgrade to anything newer, it could fail on those systems that are still using Hibernate 5.2.

In your case, you can probably exclude that dependency in Maven, when declaring the hibernate-types-52 artifact.

Since I haven't used JBoss or WildFly since 2008,  I don't know how they handle dependencies, so I can't help you with that. 

If you find a solution, it would be great if you could post it here to help others in the future.

**Comment by JensPiegsa** [comment]
Thanks for your answer. Your suggestion drove me in the right direction. I was able to solve the issue.

1. I excluded the transitive dependency via `pom.xml`:

```xml
    <dependencies>
        <dependency>
            <groupId>com.vladmihalcea</groupId>
            <artifactId>hibernate-types-52</artifactId>
            <version>2.10.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.hibernate.common</groupId>
                    <artifactId>hibernate-commons-annotations</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
```

2. And declared the additional WildFly module depenndency in `/src/main/webapp/WEB-INF/jboss-deployment-structure.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.0">
	<deployment>
		<dependencies>
			<module name="org.hibernate.commons-annotations" />
		</dependencies>
	</deployment>
</jboss-deployment-structure>
```

**Comment by vladmihalcea** [comment]
Cool. Thanks for sharing your solution.
