### ISSUE TITLE
ReflectionUtils.getGenericTypes throws ClassCastException when using Kotlin Enums

### ISSUE THREAD

**Issue by fdubuisson** [vladmihalcea/hibernate-types#300]
With version 2.10.2 and this entity:

```
@Entity
@Table(name = "tracks")
@TypeDefs(
    TypeDef(name = "string-array", typeClass = StringArrayType::class),
    TypeDef(name = "int-array", typeClass = IntArrayType::class),
    TypeDef(name = "json", typeClass = JsonStringType::class),
    TypeDef(name = "jsonb", typeClass = JsonBinaryType::class),
    TypeDef(name = "jsonb-node", typeClass = JsonNodeBinaryType::class),
    TypeDef(name = "json-node", typeClass = JsonNodeStringType::class),
)
class Track(
    @Id
    val id: String,
    @Type(type = "jsonb")
    @Column(columnDefinition = "jsonb")
    var degrees: Set<Degree>
)

enum class Degree {
   MASTER,
   BACHELOR
}
```

At start, we get the following error:
```
Caused by: org.hibernate.MappingException: Could not instantiate Type: com.vladmihalcea.hibernate.type.json.JsonBinaryType
	at org.hibernate.type.TypeFactory.type(TypeFactory.java:113) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.type.TypeFactory.byClass(TypeFactory.java:70) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.type.TypeResolver.heuristicType(TypeResolver.java:126) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:484) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:466) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.mapping.Property.isValid(Property.java:227) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:624) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.mapping.RootClass.validate(RootClass.java:267) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:354) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:465) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1259) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58) ~[spring-orm-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365) ~[spring-orm-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:391) ~[spring-orm-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 21 common frames omitted
Caused by: java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.WildcardTypeImpl and java.lang.Class are in module java.base of loader 'bootstrap')
	at com.vladmihalcea.hibernate.type.util.ReflectionUtils.getGenericTypes(ReflectionUtils.java:550) ~[hibernate-types-52-2.10.2.jar:na]
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.validatePropertyType(JsonTypeDescriptor.java:184) ~[hibernate-types-52-2.10.2.jar:na]
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.setPropertyClass(JsonTypeDescriptor.java:176) ~[hibernate-types-52-2.10.2.jar:na]
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.setParameterValues(JsonTypeDescriptor.java:71) ~[hibernate-types-52-2.10.2.jar:na]
	at com.vladmihalcea.hibernate.type.json.JsonBinaryType.setParameterValues(JsonBinaryType.java:84) ~[hibernate-types-52-2.10.2.jar:na]
	at org.hibernate.type.TypeFactory.injectParameters(TypeFactory.java:126) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.type.TypeFactory.type(TypeFactory.java:108) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	... 34 common frames omitted
```

No error when using `String` instead of `enum`.

**Comment by vladmihalcea** [comment]
I've never used Kotlin, and I don't think I'll use it any time soon. For this reason, this library is only tested with Java. It might work with Kotlin, but there's no guarantee.

If you think you can provide a fix that doesn't break anything in Java, then I'll review it when I have some time.

**Comment by fdubuisson** [comment]
With the following code change in `ReflectionUtils`, there is no more crash but I can't check if this brings other issues (not able to have working setup to run the tests):

```
    public static Set<Class> getGenericTypes(ParameterizedType parameterizedType) {
        Set<Class> genericTypes = new LinkedHashSet<>();
        for (Type genericType : parameterizedType.getActualTypeArguments()) {
            genericTypes.add(genericType.getClass()); // <----
        }
        return genericTypes;
    }
```

**Comment by vladmihalcea** [comment]
Send me a Pull Request so that I can test and integrate it. If the tests run, I could release a patch version with it.

**Comment by fdubuisson** [comment]
done: https://github.com/vladmihalcea/hibernate-types/pull/301

**Comment by vladmihalcea** [comment]
Great. I'll check it out and integrate it if everything works fine.

**Comment by vladmihalcea** [comment]
Fixed.
