### ISSUE TITLE
Polymorphic JSON exception

### ISSUE THREAD

**Issue by piotrooo** [vladmihalcea/hibernate-types#306]
Hello, I facing with following problem:

I have following json in db column:

```
[
  {
    "typeComment": "ADD_CONVERSATION",
    "date": "2021-03-22 11:32",
    "phoneNumber": "123456789",
    "sourceName": "test"
  },
  {
    "typeComment": "PROPERTY",
    "property": "tag",
    "oldValue": "",
    "newValue": "tag1"
  }
]
```

Entity looks:

```java
@TypeDefs({
        @TypeDef(name = "json", typeClass = JsonBinaryType.class)
})
public class Table {
    @Type(type = "jsonb")
    @Column(name = "comments", columnDefinition = "json")
    private List<Comment> comments;
}
```

Comment.java
```java
@JsonTypeInfo(use = NAME, include = EXISTING_PROPERTY, property = "typeComment", visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = AddConversationComment.class, name = "ADD_CONVERSATION"),
        @JsonSubTypes.Type(value = PropertyComment.class, name = "PROPERTY")
})
@JsonIgnoreProperties(ignoreUnknown = true)
public abstract class Comment {
    private TypeComment typeComment;

    public TypeComment getTypeComment() {
        return typeComment;
    }

    public Comment setTypeComment(TypeComment typeComment) {
        this.typeComment = typeComment;
        return this;
    }
}
```

AddConversationComment.java
```java
@JsonPropertyOrder({"typeComment", "date", "phoneNumber", "sourceName"})
public class AddConversationComment extends Comment {
    @JsonFormat(shape = STRING, pattern = "yyyy-MM-dd HH:mm", timezone = "Europe/Warsaw")
    private Instant date;
    private String phoneNumber;
    private CallSource source;
    private String sourceName;

    // getters / setters removed for brevity
}
```

PropertyComment.java
```java
@JsonPropertyOrder({"typeComment", "change", "property", "oldValue", "newValue"})
public class PropertyComment extends Comment {
    private ChangePropertyType change;
    private Property property;
    private String oldValue;
    private String newValue;
    
    // getters / setters removed for brevity
}
```

When I fetch record from db I get following exception:

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'PROPERTY' as a subtype of `AddConversationComment`: Class `PropertyComment` not subtype of `AddConversationComment`
 at [Source: (byte[])"[{"typeComment":"ADD_CONVERSATION","date":"2021-03-22 11:32","phoneNumber":"746741829","sourceName":"test"},{"typeComment":"PROPERTY","change":"start","property":"tag","oldValue":"","newValue":"tag1"}]"; line: 1, column: 141] (through reference chain: java.util.ArrayList[1])
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1780)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:194)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:115)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1197)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3529)
	at com.vladmihalcea.hibernate.type.util.ObjectMapperWrapper.fromBytes(ObjectMapperWrapper.java:66)
```

It looks like [here](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-52/src/main/java/com/vladmihalcea/hibernate/type/util/ObjectMapperJsonSerializer.java#L28) `ObjectMapperJsonSerializer` takes type of the first list element and set rest of list to use this type, which is not true. Rather that it should take a base class of first element (`Comment` in my case) and deserialize it using this base type. Am I worng? Or I missed something?

**Comment by vladmihalcea** [comment]
Polymorphism is not supported. You'll need to extend the `JsonBinaryType` and the `JsonBinarySqlTypeDescriptor` and provide a way to encode/decode the actual type so that you can instantiate the right class type when loading from the DB.

**Comment by Neil-Wan** [comment]
Hi @piotrooo , have you resolved this problem? I got the exact same error as you, i.e. it takes the type of the first list element and sets the rest of the list to use this type, rather than taking a base class of the first element.

**Comment by stoykobogev** [comment]
Hello, I'm leaving a comment for anyone struggling with this in the future.
The issue is that your parent class/interface (in the above case it's `Comment`) needs to implement `Serializable`.
During serialization of a collection the library is determining a type and checks if the class is implementing `Serializable` otherwise it picks the first element in the collection and uses that type (in the above case it's `AddConversationComment`).
