### ISSUE TITLE
Cannot be transformed to Json object

### ISSUE THREAD

**Issue by dgks0n** [vladmihalcea/hibernate-types#32]
Hi all,

I'm using ```hibernate-types``` to serialize/deserialize list of my object with MySQL as below:

```
public class DefaultMessage {
    # few properties here with its getter/setter
}

public class Project {
    @Type(type = "json")
    @Column(name = "default_messages", columnDefinition = "json")
    private List<DefaultMessage> defaultMessages;

    # Getter/setter
}
```

Of course, I have defined map supper class and @TypeDef but it always return cannot be transformed to Json object.

Exception:
```
2018-05-29 19:00:10,343 WARN  [http-nio-8088-exec-4] ? (:) - The given string value: [B@4ad8cfea cannot be transformed to Json object
java.lang.IllegalArgumentException: The given string value: [B@4ad8cfea cannot be transformed to Json object
	at com.vladmihalcea.hibernate.type.util.ObjectMapperWrapper.fromString(ObjectMapperWrapper.java:52) ~[hibernate-types-52-2.2.1.jar:?]
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.fromString(JsonTypeDescriptor.java:87) ~[hibernate-types-52-2.2.1.jar:?]
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.wrap(JsonTypeDescriptor.java:110) ~[hibernate-types-52-2.2.1.jar:?]
	at com.vladmihalcea.hibernate.type.json.internal.AbstractJsonSqlTypeDescriptor$1.doExtract(AbstractJsonSqlTypeDescriptor.java:34) ~[hibernate-types-52-2.2.1.jar:?]
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:261) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:247) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:333) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:2868) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1747) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1673) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.loader.Loader.getRow(Loader.java:1562) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:732) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.loader.Loader.processResultSet(Loader.java:991) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.loader.Loader.doQuery(Loader.java:949) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:341) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.loader.Loader.doList(Loader.java:2692) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.loader.Loader.doList(Loader.java:2675) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2507) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.loader.Loader.list(Loader.java:2502) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:502) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:392) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1490) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1445) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1414) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1463) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'B': was expecting ('true', 'false' or 'null')
```

Can you give me few suggestions to solve problem?

Thank you!

**Comment by dgks0n** [comment]
@vladmihalcea I don't think so, this is real JSON string that stored in MySQL: `[]`

I'm using the `getEntityManager().find(type, id)` method for loading my record and parser the field `default_messages` with its data `[]` into List<DefaultMessage> but could not. It throws exception as issue named.

Thanks

**Comment by dgks0n** [comment]
I checked your lib and I through the problem related to this class:

```
public abstract class AbstractJsonSqlTypeDescriptor implements SqlTypeDescriptor {

    @Override
    public int getSqlType() {
        return Types.OTHER;
    }

    @Override
    public boolean canBeRemapped() {
        return true;
    }

    @Override
    public <X> ValueExtractor<X> getExtractor(final JavaTypeDescriptor<X> javaTypeDescriptor) {
        return new BasicExtractor<X>(javaTypeDescriptor, this) {
            @Override
            protected X doExtract(ResultSet rs, String name, WrapperOptions options) throws SQLException {
                return javaTypeDescriptor.wrap(rs.getObject(name), options);
            }
        };
    }

}
```
In fact, the ```rs.getObject(name)``` should return real value of field but it always return instance id. For example: `B@4ad8cfea`

Why id does not return correctly?

**Comment by vladmihalcea** [comment]
Just fork the repo and run the tests and you'll see they all run just fine for both PostgreSQL and MySQL.

**Comment by vladmihalcea** [comment]
@dgks0n Try with version 2.2.2. I made the JsonStringTYpe use getString instead of getObject.

**Comment by xudaile** [comment]
@dgks0n @vladmihalcea I have the same problem. How to solve the problem in the end？
@Type(type = "jsonb")
    @Column(name = "research_age_group",columnDefinition = "jsonb")
    private List<ResearchReportAgeGroup> researchAgeGroup=new ArrayList<>();
use JPA can be save ,but not be transform
 The given string value: [{"pois": [{"city": "北京", "name": "测试POI", "type": "交通枢纽", "poi_id": "B0001232", "address": "北京市天安门附近", "location": "POINT(116.373699 39.917103)"}], "type": "交通枢纽"}] cannot be transformed to Json object

**Comment by deviant-studio** [comment]
same issue with deserializing map `Map<Long, Metrics>`
serialization works ok, but extraction throws:
```
Can not deserialize Map key of type java.lang.Long from String "Click Through Rate": not a valid representation, problem: (java.lang.NumberFormatException) For input string: "Click Through Rate"
```

**Comment by vladmihalcea** [comment]
Looks like the key was not saved properly. Try to replicate it with a test case.

**Comment by ffroliva** [comment]
Hi I have the following scenario:

I have a Map<Enum, Double> it gets saves correct, but I am not being able to deserialize it.

Any suggestions?

`Caused by: java.lang.IllegalArgumentException: The given string value: {"EQUITY": 2.0, "CASH_OR_CASH_EQUIVALENT": 1.0} cannot be transformed to Json object
	at com.vladmihalcea.hibernate.type.util.ObjectMapperWrapper.fromString(ObjectMapperWrapper.java:52)
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.fromString(JsonTypeDescriptor.java:105)
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.wrap(JsonTypeDescriptor.java:163)
	at com.vladmihalcea.hibernate.type.json.internal.AbstractJsonSqlTypeDescriptor$1.doExtract(AbstractJsonSqlTypeDescriptor.java:34)`

**Comment by vladmihalcea** [comment]
Try to create a replicating test case that proves the issue using one of the exists tests as a template. Once you replicated it, send a Pull Request with the test case.

**Comment by ffroliva** [comment]
I was able to solve the problem by adding  jackson-datatype-guava in my
project. Maybe it would be nice if added it to your project since it might
be a very common practice to depend on guavas Immutable classes as I do. Or
you can document you lib informing that dependency.

<dependency>
    <groupId>com.fasterxml.jackson.datatype</groupId>
    <artifactId>jackson-datatype-guava</artifactId>
    <version>${jackson.version}</version>
</dependency>


Regards,

Flávio Oliva

Em sex., 24 de abr. de 2020 às 17:36, Vlad Mihalcea <
notifications@github.com> escreveu:

**Comment by vladmihalcea** [comment]
Hibernate Types does not require the Jackson Guava dependency. Your application needs it because you are using `ImmutableMap`.

**Comment by guptapavan31** [comment]
> jackson-datatype-guava

Can you please provide the example how it actually got resolved.

**Comment by vladmihalcea** [comment]
@guptapavan31 check out this solution provided by @ffroliva 

> I was able to solve the problem by adding jackson-datatype-guava in my project. Maybe it would be nice if you could add it to your project since it might be a very common practice to depend on guavas Immutable classes as I do. Or you can document you lib informing that dependency. ``` <dependency> <groupId>com.fasterxml.jackson.datatype</groupId> <artifactId>jackson-datatype-guava</artifactId> <version>${jackson.version}</version> </dependency> ``` Regards, Flávio Oliva

**Comment by guptapavan31** [comment]
> @guptapavan31 check out this solution provided by @ffroliva
> 
> > I was able to solve the problem by adding  jackson-datatype-guava in my
> > project. Maybe it would be nice if you could add it to your project since it might
> > be a very common practice to depend on guavas Immutable classes as I do. Or
> > you can document you lib informing that dependency.
> 
> ```
> <dependency>  
>     <groupId>com.fasterxml.jackson.datatype</groupId>
>     <artifactId>jackson-datatype-guava</artifactId>
>     <version>${jackson.version}</version>
> </dependency>
> ```

@vladmihalcea By just adding dependency does not solve the issue. There would have be something done to actually solve it... The code changes or something. I am expecting that answer.

**Comment by vladmihalcea** [comment]
If you find a solution, don't forget to add it here to help others in the future.

**Comment by hamiller** [comment]
Try to give your JsonB-Class an `implements Serializable` - at least that worked for me

**Comment by FaustXVI** [comment]
> Try to give your JsonB-Class an `implements Serializable` - at least that worked for me

This solved my issue ! Thanks !

**Comment by harshitpandey091wetrade** [comment]
> Try to give your JsonB-Class an `implements Serializable` - at least that worked for me

This worked for me as well. Any reasoning around this  though?
