### ISSUE TITLE
Unable to load class [com.vladmihalcea.hibernate.type.array.ListArrayType]

### ISSUE THREAD

**Issue by liuzqt** [vladmihalcea/hibernate-types#323]
I basically followed the tutorial here  https://vladmihalcea.com/postgresql-array-java-list/

my entity declaration is as below:
```
@Entity
@DynamicInsert
@TypeDef(name = "list-array", typeClass = ListArrayType.class)
public class MapObject {
    @Id
    @Generated(GenerationTime.INSERT)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long vid;
    // @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "oid", columnDefinition = "BIGSERIAL", nullable = true)
    @Generated(GenerationTime.INSERT)
    private Long oid;

    private String msg;

    @Type(type = "list-array")
    @Column(columnDefinition = "varchar[]")
    private List<String> tags;
}
```

got this error:

```
Exception in thread "main" org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [com.vladmihalcea.hibernate.type.array.ListArrayType]
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:136)
        at org.hibernate.boot.internal.ClassLoaderAccessImpl.classForName(ClassLoaderAccessImpl.java:67)
        at org.hibernate.cfg.annotations.SimpleValueBinder.fillSimpleValue(SimpleValueBinder.java:536)
        at org.hibernate.cfg.SetSimpleValueTypeSecondPass.doSecondPass(SetSimpleValueTypeSecondPass.java:25)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1693)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1651)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:295)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
        at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
        at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:689)
        at com.ziqi.App.main(App.java:22)
```

my maven dependency:
```
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.postgresql/postgresql -->
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>42.2.20</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.hibernate/hibernate-core -->
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-core</artifactId>
      <version>5.4.32.Final</version>
    </dependency>
    <dependency>
      <groupId>com.vladmihalcea</groupId>
      <artifactId>hibernate-types-52</artifactId>
      <version>2.11.1</version>
    </dependency>

  </dependencies>
```

**Comment by vladmihalcea** [comment]
This is what you can do:

- fork the repository
- run the [`ListArrayTypeTest`](https://github.com/vladmihalcea/hibernate-types/blob/10b82db716695c5a17447ab83fd0bd891011a9fc/hibernate-types-52/src/test/java/com/vladmihalcea/hibernate/type/array/ListArrayTypeTest.java) in debug mode and see why `org.hibernate.cfg.annotations.SimpleValueBinder.fillSimpleValue(SimpleValueBinder.java:536)` works fine in my test
- then do a debug in your application and see what it differs at the `org.hibernate.cfg.annotations.SimpleValueBinder.fillSimpleValue(SimpleValueBinder.java:536)` line

Most likely, this is a class loading issue.
