### ISSUE TITLE
Add support for half-hour time zones in ZonedDateTime

### ISSUE THREAD

**Issue by adeebin** [vladmihalcea/hibernate-types#329]
You had given a great and to the point implementation of range types. I am pretty sure that 1000s may be using this.
I have come across an issue, related to parsing of zoned date-time after saving. Please review whether it's worth looking into.

I have initialised an entity with a zoned timestamp range using

    Range.closedInfinite(ZonedDateTime.now(ZoneOffset.UTC));

On first save (insert), an entry is made in postgres database with time range as 

    id=1, [2021-07-01 17:48:09.97322+05:30, )

Due to some custom requirements, I am loading the object using a native query
```
SELECT 	range_id,	lower(zoned_timerange) as from_time, upper(zoned_timerange) as till_time
FROM	z_buddy where <some condition>
```

The lower and upper are read as timestamptz and is used to update and create entities
Existing:	Range.closedOpen(current.lower(), ZonedDateTime.now(ZoneOffset.UTC)); // id = 1, [2021-07-01 17:48:09.97322+05:30, 2021-07-05 18:47:14.455061+05:30)
New:	Range.closedInfinite(ZonedDateTime.now(ZoneOffset.UTC)); // id is null, [2021-07-05 18:47:14.455061+05:30, )
I.e., on second, save, I close the first record and attempt to create a copy with a new starting range

In my observation, spring tries to load the entity after save, and during that, a parse exception is being thrown when we parse the string according to ZONE_DATE_TIME .
If my observation is right, though the string is in "yyyy-MM-dd HH:mm:ss[.nnnnnn]Z", the matching fails.

As we are suppressing the original exception; we are getting exception on default parse logic of ZonedDateTime
```
private static Function<String, ZonedDateTime> parseZonedDateTime() {
        return s -> {
            try {
                return ZonedDateTime.parse(s, ZONE_DATE_TIME);
            } catch (DateTimeParseException e) {
                return ZonedDateTime.parse(s);
            }
        };
    }
```

I could not find a pattern that works (using DateTimeFormatter); but when I have copy-pasted your code and given a custom parse function, for matching 2021-07-05 18:47:14.455061+05:30, it started working.

In my observation, the definition of formatting at postgres is open and hence, please review whether we can make this pattern configurable, or extendable.

Entity:
--------
```
@Entity(name = "Buddy")
@Table(name = "z_buddy")
@TypeDef(typeClass = PostgreSQLRangeType.class, defaultForType = Range.class)
public class ZonedBuddy {
    @Id
    @Column(name = "range_id") // bigserial
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // other attribues ...
    @Column(name = "zoned_timerange", columnDefinition = "tstzrange") //
    private Range<ZonedDateTime> zonedTimeRange; //
}
```

Stack Trace:
----------------
```
java.time.format.DateTimeParseException: Text '2021-07-05 18:47:14.455061+05:30' could not be parsed at index 10
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046) ~[na:na]
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948) ~[na:na]
	at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:598) ~[na:na]
	at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:583) ~[na:na]
	at com.vladmihalcea.hibernate.type.range.Range.lambda$5(Range.java:570) ~[main/:na]
	at java.base/java.util.function.Function.lambda$compose$0(Function.java:68) ~[na:na]
	at com.vladmihalcea.hibernate.type.range.Range.ofString(Range.java:354) ~[main/:na]
	at com.vladmihalcea.hibernate.type.range.Range.zonedDateTimeRange(Range.java:521) ~[main/:na]
	at com.vladmihalcea.hibernate.type.range.PostgreSQLRangeType.get(PostgreSQLRangeType.java:88) ~[main/:na]
	at com.vladmihalcea.hibernate.type.range.PostgreSQLRangeType.get(PostgreSQLRangeType.java:1) ~[main/:na]
	at com.vladmihalcea.hibernate.type.ImmutableType.nullSafeGet(ImmutableType.java:98) ~[hibernate-types-52-2.10.2.jar:na]
	at com.vladmihalcea.hibernate.type.ImmutableType.hydrate(ImmutableType.java:290) ~[hibernate-types-52-2.10.2.jar:na]
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:3135) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1870) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.Loader.hydrateEntityState(Loader.java:1798) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1771) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	
	at org.hibernate.loader.Loader.getRow(Loader.java:1623) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:740) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.Loader.getRowsFromResultSet(Loader.java:1039) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.Loader.processResultSet(Loader.java:990) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.Loader.doQuery(Loader.java:959) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:349) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:319) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.Loader.loadEntity(Loader.java:2422) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:72) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:61) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.doLoad(AbstractEntityPersister.java:4442) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4432) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:569) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:537) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:208) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:332) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:108) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:74) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:113) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1186) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1175) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.internal.SessionImpl.access$2100(SessionImpl.java:193) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2786) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.lambda$load$1(SessionImpl.java:2767) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.perform(SessionImpl.java:2723) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2767) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.internal.SessionImpl.get(SessionImpl.java:988) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]

	at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:306) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:172) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:70) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]

	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:793) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:780) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:362) ~[spring-orm-5.3.3.jar:5.3.3]
	at com.sun.proxy.$Proxy152.merge(Unknown Source) ~[na:na]
	at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:311) ~[spring-orm-5.3.3.jar:5.3.3]

	at com.sun.proxy.$Proxy152.merge(Unknown Source) ~[na:na]
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:560) ~[spring-data-jpa-2.4.3.jar:2.4.3]
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.saveAll(SimpleJpaRepository.java:591) ~[spring-data-jpa-2.4.3.jar:2.4.3]
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.saveAll(SimpleJpaRepository.java:78) ~[spring-data-jpa-2.4.3.jar:2.4.3]
```

**Comment by vladmihalcea** [comment]
At the moment, I don't have the time to investigate issues in my spare time, so there are two possibilities to address this issue:

- create a replicating test case, investigate the issue, find a solution, fix the framework, and provide a Pull Request 
- Or, I could investigate the issue for you via [consulting](https://vladmihalcea.com/consulting/) if the company that's paying you considers that's cheaper to pay me to fix it.

**Comment by adeebin** [comment]
I have raised https://github.com/vladmihalcea/hibernate-types/pull/331/files with my suggested fix

**Comment by vladmihalcea** [comment]
Thanks, I'll review it when I have some time.

**Comment by vladmihalcea** [comment]
Merged PR. Thanks for your contribution.
