### ISSUE TITLE
Null Pointer Exception with PSQL ArrayType Mapping 

### ISSUE THREAD

**Issue by bmistry13** [vladmihalcea/hibernate-types#335]
Hi,

I am getting an NPE exception when I compile code using Mac OS and when compile the same CODE using Linux, the error is not seen.  

abstractArrayTypeDescriptor.getSqlArrayType()  is returning NULL and PSQL Driver throws NPE.    Can you please let me know why is this behavior?

PSQL Driver:

```
public String getTypeForAlias(String alias) {
    String type = typeAliases.get(alias);
    if (type != null) {
      return type;
    }
    if (alias.indexOf('"') == -1) {   // THIS LINE THROWS NPE SINCE alias is null ** 
      type = typeAliases.get(alias.toLowerCase());
      if (type != null) {
        return type;
      }
    }
    return alias;
  }

```
```
Caused by: javax.persistence.RollbackException: Error while committing the transaction
        at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:81)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:562)
        ... 122 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.postgresql.jdbc.TypeInfoCache.getTypeForAlias(TypeInfoCache.java:675)
        at org.postgresql.jdbc.TypeInfoCache.getPGArrayType(TypeInfoCache.java:519)
        at org.postgresql.jdbc.PgConnection.createArrayOf(PgConnection.java:1375)
        at org.postgresql.jdbc.PgConnection.createArrayOf(PgConnection.java:1399)
        at org.apache.commons.dbcp2.DelegatingConnection.createArrayOf(DelegatingConnection.java:827)
        at org.apache.commons.dbcp2.DelegatingConnection.createArrayOf(DelegatingConnection.java:827)
        at org.apache.commons.dbcp2.DelegatingConnection.createArrayOf(DelegatingConnection.java:827)
        at com.vladmihalcea.hibernate.type.array.internal.ArraySqlTypeDescriptor$1.doBind(ArraySqlTypeDescriptor.java:36)
        at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:73)
        at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:276)
        at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:271)
        at org.hibernate.type.AbstractSingleColumnStandardBasicType.nullSafeSet(AbstractSingleColumnStandardBasicType.java:39)
        at org.hibernate.persister.entity.AbstractEntityPersister.dehydrate(AbstractEntityPersister.java:2995)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3292)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3828)
        at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
        at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:348)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1362)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:453)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3212)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2380)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:447)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
        ... 123 common frames omitted
```

Thanks,
Bhavesh

**Comment by vladmihalcea** [comment]
I have no idea. You can investigate it and provide a replicating test case and a fix proposal. Looking forward to seeing your contribution.

**Comment by bmistry13** [comment]
@vladmihalcea, can you please give background on how does abstractArrayTypeDescriptor.getSqlArrayType()  is being set ?  so I can check further.  We have compile-time weaving spring aop.  Does it have any impact ?  How does ArraySqlTypeDescriptor figure out it type ?

**Comment by bmistry13** [comment]
Hi Entity uses multiple types as shown below for service column mapping  is coming as EnumArrayTypeDescriptor which should have been StringArrayTypeDescriptor.  EnumArrayTypeDescriptor.getSqlArrayType() is returning null for service column.  But when I compile the same code with Linux, it is coming as StringArrayTypeDescriptor.  What could cause this?


```
@TypeDefs({
    @TypeDef(
        name = "string-array",
        typeClass = StringArrayType.class
    ),
    @TypeDef(
        name = "int-array",
        typeClass = IntArrayType.class
    ),
		@TypeDef(
				name = "pgsql_enum",
				typeClass = PostgreSQLEnumType.class
		)
})
```

	```
@Type( type = "string-array" )
	@Column(name = "services")
	private String[] services;
```

**Comment by vladmihalcea** [comment]
Check out [this test case](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-52/src/test/java/com/vladmihalcea/hibernate/type/array/ArrayTypeTest.java) that looks similar to yours.

Download the project and run that test case and compare to yours.
