### ISSUE TITLE
NullPointerException on JsonBlobType

### ISSUE THREAD

**Issue by Scuilion** [vladmihalcea/hibernate-types#370]
Adding the following test to OracleJsonBinaryTypeTest.java
```
    @Test
    public void searchJsonBlobColumn() {
        doInJPA(entityManager -> {
            List<Participant> participantList = entityManager
                .createNativeQuery("SELECT id, version, metadata, ticket, event_id FROM PARTICIPANT p WHERE p.METADATA.country = 'Romania'")
                .unwrap(NativeQuery.class)
                .addScalar("metadata", new JsonBlobType())
                .getResultList();

            assertEquals(1, participantList.size());
            assertEquals("Romania", participantList.get(0).getMetadata());
        });
    }
```
Will fail with a NullPointerException
```
java.lang.NullPointerException
	at java.base/java.lang.Class.isAssignableFrom(Native Method)
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.fromString(JsonTypeDescriptor.java:104)
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.wrap(JsonTypeDescriptor.java:165)
	at org.hibernate.type.descriptor.sql.BlobTypeDescriptor$1.doExtract(BlobTypeDescriptor.java:48)
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:249)
	at org.hibernate.loader.custom.ScalarResultColumnProcessor.extract(ScalarResultColumnProcessor.java:54)
	at org.hibernate.loader.custom.ResultRowProcessor.buildResultRow(ResultRowProcessor.java:83)
	at org.hibernate.loader.custom.ResultRowProcessor.buildResultRow(ResultRowProcessor.java:60)
	at org.hibernate.loader.custom.CustomLoader.getResultColumnOrRow(CustomLoader.java:412)
	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:765)
	at org.hibernate.loader.Loader.getRowsFromResultSet(Loader.java:1034)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:985)
	at org.hibernate.loader.Loader.doQuery(Loader.java:954)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:344)
	at org.hibernate.loader.Loader.doList(Loader.java:2838)
	at org.hibernate.loader.Loader.doList(Loader.java:2820)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2652)
	at org.hibernate.loader.Loader.list(Loader.java:2647)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:338)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2170)
	at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1178)
	at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:176)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
	at org.hibernate.query.Query.getResultList(Query.java:165)
	at com.vladmihalcea.hibernate.type.json.OracleJsonBinaryTypeTest.lambda$searchJsonBlobColumn$4(OracleJsonBinaryTypeTest.java:116)
	at com.vladmihalcea.hibernate.util.AbstractTest.doInJPA(AbstractTest.java:449)
	at com.vladmihalcea.hibernate.type.json.OracleJsonBinaryTypeTest.searchJsonBlobColumn(OracleJsonBinaryTypeTest.java:110)
```
This can be fixed by declaring the type
`.addScalar("metadata", new JsonBlobType(Location.class))`
but the null pointer gave me the run around for a bit. Might be helpful to have a better error.

**Comment by vladmihalcea** [comment]
Here's what you need to do:

1. Create a replicating test case
2. Add a fix if you spotted the problem 
3. Send a Pull Request 

I'll review it when it's done.

**Comment by Scuilion** [comment]
The problem is, I don't know what you'd like for the desired outcome. 

Is no type definition appropriate, or should it always fail? If it should fail, then what Exception should it be throwing? If it shouldn't fail, what `type` should it default to?

**Comment by vladmihalcea** [comment]
The solution is probably to pass the expected Java Object type to the `HibernateJsonBlobType` when calling addScalar, similar to [this](https://github.com/vladmihalcea/hibernate-types/blob/e419ad5089ff7b8f4746694dd6b0b19dc31866d4/hibernate-types-43/src/test/java/com/vladmihalcea/hibernate/type/json/PostgreSQLJsonStringPropertyTest.java#L89).

**Comment by Scuilion** [comment]
Does it make sense to have a zero arg constructor.

**Comment by vladmihalcea** [comment]
Yes, of course it makes sense. An entity knows the type of each property, so the property type is available to the Hibernate Type.

For query projections, that type has to be provided explicitly.
