### ISSUE TITLE
Support for SchemaUpdate

### ISSUE THREAD

**Issue by joselfreire** [vladmihalcea/hibernate-types#398]
Using the JsonType.class for database technology agnostic configuration fails when using SchemaUpdate, with error "No Dialect mapping for JDBC type: 1111", at least for SQL Server Dialects, but I suppose it will fail for all Dialects.

For what I've looked at, there is no information available for Hibernate to create the DDL script. 

The stack trace is (using hibernate-types-52 2.14.0 and hibernate 5.4.31.Final):
```
 Caused by: org.hibernate.MappingException: No Dialect mapping for JDBC type: 1111
	at org.hibernate.dialect.TypeNames.get(TypeNames.java:71)
	at org.hibernate.dialect.TypeNames.get(TypeNames.java:103)
	at org.hibernate.dialect.Dialect.getTypeName(Dialect.java:403)
	at org.hibernate.mapping.Column.getSqlType(Column.java:238)
	at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:96)
	at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:30)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.createTable(AbstractSchemaMigrator.java:279)
	at 
 org.hibernate.tool.schema.internal.GroupedSchemaMigratorImpl.performTablesMigration(GroupedSchemaMigratorImpl.java:71)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.performMigration(AbstractSchemaMigrator.java:207)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:114)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:93)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:62)
        ...
```

One approach could be enhancing SQLServerDialect with the new type, however, type 1111 is "OTHER", and that doesn't feel like the correct approach.

**Comment by vladmihalcea** [comment]
The Hibernate Types library is just a plugin. A plugin does not control the Hibernate ORM core. The feature you need can only be implemented in the Hibernate framework, and you can do it too since Hibernate is OSS.

Since I'm no longer working for Red Hat, I will never have the time to do it myself unless your company wants to hire me to investigate it and find a solution.
