### ISSUE TITLE
PostgreSql Problem Querying JSON Field

### ISSUE THREAD

**Issue by khamburg-dev-sk** [vladmihalcea/hibernate-types#402]
I have a table in Postgres with a JSONB column that is being used to store an array of strings, e.g. ["a","b","c"]. 

```sql
CREATE TABLE mytable ("id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "field1" text NOT NULL,
                          "field2" text NOT NULL unique,
                          "json_field" jsonb, // contains json array
                          "other_json_field" jsonb,
                          "created" timestamp
) with (oids = false);
```

Java class: 

```java
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity(name="mytable")
@TypeDef(
        name = "json",
        typeClass = JsonType.class
)
public class MyRecord {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    private String field1;
    private String field2;

    @Type(type = "json")
    @Column(columnDefinition = "jsonb") // contains json array ["a","b","c"]
    private String jsonField;

    @Type(type = "json")
    @Column(columnDefinition = "jsonb")  // contains json object { "prop1": "abc", "prop2": "def" }
    private String otherJsonField;

    private Timestamp created;

}
```

I need to search for all records matching a single element of that json array. I also need indexing on that column using a GIN index. The docs suggest that you must use an operator such as "?" or "@>" to take advantage of indexing. My initial query used "?" (but Hibernate thought it was a parameter):

```java
 // Doesn't work due to ? operator confusion -- error is "Mixing of ? parameters and other forms like ?1 is not supported!"
@Query(value = "select * from mytable  where jsonField ? :searchValue", nativeQuery = true)
List<MyRecord> findByJsonField(String searchValue);
```

I wasn't able to find a way to escape the question mark, so I switched to using the "@>" operator and constructed a json array with one item (my search value) in my search:

```java
@PersistenceContext
private EntityManager em;

// Doesn't work -- "No Dialect mapping for JDBC type: 1111"
@Override
public List<MyRecord> findByJsonField(String searchValue) {
    return (List<MyRecord>) em.createNativeQuery("select * from mytable where json_field @> '[\"" + searchValue + "\"]\\:\\:jsonb").getResultList();  // tried with and without the ::jsonb
}
``` 

This gives the message "No Dialect mapping for JDBC type: 1111". I am using hibernate-types:

```groovy
build.gradle:
plugins {
    id 'org.springframework.boot' version '2.3.2.RELEASE'

implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
implementation group: 'com.vladmihalcea', name: 'hibernate-types-52', version: 'hibernate_types_version'
implementation group: 'org.postgresql', name: 'postgresql', version: postgres_version

gradle.properties:
hibernate_types_version=2.14.0
postgres_version=42.3.1
```

I have tried creating a custom dialect (although I'm not sure this is required when using hibernate-types):

```java
public class PostgreSQL95JsonDialect extends PostgreSQL95Dialect {

    public PostgreSQL95JsonDialect() {
        super();
        registerHibernateType(Types.OTHER, JsonBinaryType.class.getName());
    }
}

application.yml:
jpa:
  hibernate:
    naming:
      physical-strategy: com.my.PostgresPhysicalNamingStrategy # adjusts field names - not relevent but thought I would mention it
  properties:
    hibernate:
      dialect:
        config: com.my.PostgreSQL95JsonDialect
```

The dialect didn't fix the issue. I also tried configuring the dialect in code:

```java
@Configuration
public class HibernateConfig {

    @Bean
    public PostgreSQL95JsonDialect customDialect() {
        return new PostgreSQL95JsonDialect();
    }

    @Bean
    public PostgresPhysicalNamingStrategy customNamingStrategy() {
        return new PostgresPhysicalNamingStrategy();
    }

}
```

Here is a snippet from my tests using a local postgres db. Notice that the second test retrieves the same sample record as the failing test.

```groovy
def "setup"() {
    rec1 = MyRecord.builder()
            .field1("ddd")
            .field2("123")
            .jsonField('["100","abc"]')
            .otherJsonField('{"prop1": "123"}')
            .build();
    rec2 = MyRecord.builder()
            .field1("ddd")
            .field2("100")
            .otherJsonField('{"prop1": "123"}')
            .build();
    myRepository.saveAll([rec1, rec1])
}

// This test fails
def "test findByJsonField"() {
    when:
    List<MyRecord> results = myRepository.findByJsonField('abc')

    then:
    results.size() == 1
}

// This test works
def "test findByOtherJsonField"() {
    when:
    List<MyRecord> results = myRepository.findByOtherJsonField("123")

    then:
    results.size() == 2
}

```

Here is the stack trace. The odd thing is that it appears that the query has already completed and the error is happening while loading the data into a java object. Interestingly, the other test retrieves the same data and it works. The other query is:

```java
@Query(value = "select * from mytable where other_json_field ->> 'prop1' = :value", nativeQuery = true)
List<MyRecord> findByOtherJsonField(@Param("value") String value);
```

```java
No Dialect mapping for JDBC type: 1111; nested exception is org.hibernate.MappingException: No Dialect mapping for JDBC type: 1111
org.springframework.orm.jpa.JpaSystemException: No Dialect mapping for JDBC type: 1111; nested exception is org.hibernate.MappingException: No Dialect mapping for JDBC type: 1111
                at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:353)
                at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255)
                at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528)
                at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
                at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
                at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
                at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at org.springframework.data.repository.core.support.ImplementationInvocationMetadata.invoke(ImplementationInvocationMetadata.java:72)
                at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:382)
                at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:205)
                at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:549)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
                at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:155)
                at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
                at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
                at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
                at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
                at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
                at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
                at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
                at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
                at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
                at com.my.PostgresRepositoryIntegrationSpec.test findByJsonField(PostgresRepositoryIntegrationSpec.groovy:61)
Caused by: org.hibernate.MappingException: No Dialect mapping for JDBC type: 1111
                at org.hibernate.dialect.TypeNames.get(TypeNames.java:71)
                at org.hibernate.dialect.TypeNames.get(TypeNames.java:103)
                at org.hibernate.dialect.Dialect.getHibernateTypeName(Dialect.java:706)
                at org.hibernate.loader.custom.JdbcResultMetadata.getHibernateType(JdbcResultMetadata.java:100)
                at org.hibernate.loader.custom.ScalarResultColumnProcessor.performDiscovery(ScalarResultColumnProcessor.java:45)
                at org.hibernate.loader.custom.CustomLoader.autoDiscoverTypes(CustomLoader.java:494)
                at org.hibernate.loader.Loader.preprocessResultSet(Loader.java:2357)
                at org.hibernate.loader.Loader.getResultSet(Loader.java:2313)
                at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2064)
                at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2026)
                at org.hibernate.loader.Loader.doQuery(Loader.java:951)
                at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:352)
                at org.hibernate.loader.Loader.doList(Loader.java:2857)
                at org.hibernate.loader.Loader.doList(Loader.java:2839)
                at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2671)
                at org.hibernate.loader.Loader.list(Loader.java:2666)
                at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:338)
                at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2139)
                at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1163)
                at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:173)
                at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1533)
                at org.hibernate.query.Query.getResultList(Query.java:165)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:409)
                at com.my.PostgresRepositoryImpl.findByJsonField(PostgresRepositoryImpl.java:24)
                at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
                at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
                ... 30 more
```

**Comment by vladmihalcea** [comment]
You can use `addScalar`, as explained in [this article](https://vladmihalcea.com/hibernate-no-dialect-mapping-for-jdbc-type/), and it will work just fine.

**Comment by khamburg-dev-sk** [comment]
I forgot to mention that I tried that, but it seems to limit the results to a single field, whereas I need the entire record. This causes me to get an error saying that it can't find a converter between string and MyRecord.

**Comment by vladmihalcea** [comment]
I could investigate it via consulting if you're interested.

**Comment by khamburg-dev-sk** [comment]
I resolved it. It turns out my entire problem was that I wasn't passing the java class in the second parameter to createNativeQuery. I changed as below and it resolved all of the problems, without the need for a custom dialect:

```java
String sql = "select * from mytable where json_field @> '[\"" + searchValue + "\"]";
return em.createNativeQuery(sql, MyRecord.class).getResultList();
```
