### ISSUE TITLE
NullPointerException in JsonType when used in ColumnResult

### ISSUE THREAD

**Issue by bioplasticlining** [vladmihalcea/hibernate-types#403]
Hello,

First of all, thanks for the library!

I've encountered a NullPointerException when trying to use one of the types in the library in a ResultSetMapping/ColumnResult.

Specifically, when I replace `JsonNode.class` with `JsonType.class` in this line https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-52/src/test/java/com/vladmihalcea/hibernate/type/json/PostgreSQLJsonNodeTypeTest.java#L200 the test gives

```
org.hibernate.MappingException: Could not instantiate Type: com.vladmihalcea.hibernate.type.json.JsonType

	at org.hibernate.type.TypeFactory.type(TypeFactory.java:113)
	at org.hibernate.type.TypeFactory.byClass(TypeFactory.java:70)
	at org.hibernate.type.TypeResolver.heuristicType(TypeResolver.java:126)
	at org.hibernate.type.TypeResolver.heuristicType(TypeResolver.java:91)
	at org.hibernate.cfg.annotations.ResultsetMappingSecondPass.doSecondPass(ResultsetMappingSecondPass.java:184)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1693)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1660)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:295)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1224)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1255)
	at com.vladmihalcea.hibernate.util.AbstractTest.newEntityManagerFactory(AbstractTest.java:271)
	at com.vladmihalcea.hibernate.util.AbstractTest.init(AbstractTest.java:74)
	...
Caused by: java.lang.NullPointerException
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.setParameterValues(JsonTypeDescriptor.java:70)
	at com.vladmihalcea.hibernate.type.json.JsonType.setParameterValues(JsonType.java:96)
	at org.hibernate.type.TypeFactory.injectParameters(TypeFactory.java:123)
	at org.hibernate.type.TypeFactory.type(TypeFactory.java:108)
	... 33 more
...
```

However replacing it with `JsonNodeBinaryType.class` passes the test, so I wasn't sure if specifying the Hibernate type is a supported use case. Seems like I would have to write a custom concrete Hibernate type to use here if I wanted to get an extraction to a Map. Maybe a better error message would be helpful to figure out what's supported / not supported?

Thanks.

**Comment by vladmihalcea** [comment]
Thanks. I'm glad you liked it.

Since you already found a way to reproduce the issue, you could try to debug it and see what's needed to be changed in order to have the test working. Once you figure out the problem, you should send me a Pull Request so that I could review it.

**Comment by vladmihalcea** [comment]
You can't replace this:

    @ColumnResult(name = "properties", type = JsonNode.class)

with this:

    @ColumnResult(name = "properties", type = JsonType.class)

The former tells that the `properties` will be a JSON object. Your change tells that the `properties` entity attribute is a Hibernate TYpe, which makes no sense.
