### ISSUE TITLE
Register the PostgreSQLGuavaRangeType only if Guava Range is available on the classpath

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hibernate-types#421]
The `HibernateTypesContributor` tries to register the `PostgreSQLGuavaRangeType`, but if the `com.google.common.collect.Range` is not found, a `NoClassDefFoundError` is thrown:

```
java.lang.NoClassDefFoundError: com/google/common/collect/Range

	at com.vladmihalcea.hibernate.type.range.guava.PostgreSQLGuavaRangeType.<clinit>(PostgreSQLGuavaRangeType.java:58)
	at com.vladmihalcea.hibernate.type.HibernateTypesContributor.contribute(HibernateTypesContributor.java:66)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:376)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:142)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1350)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1421)
```

**Comment by vladmihalcea** [comment]
Fixed.
