### ISSUE TITLE
NPE thrown by JsonTypeDescriptor.fromString

### ISSUE THREAD

**Issue by gauravgupta429** [vladmihalcea/hibernate-types#431]
Thanks for your excellent work on the Hibernate types library

I am facing below issue:
java.lang.NullPointerException: null
	at java.base/java.lang.Class.isAssignableFrom(Native Method) ~[na:na]
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.fromString(JsonTypeDescriptor.java:104) ~[hibernate-types-52-2.16.1.jar:na]
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.wrap(JsonTypeDescriptor.java:165) ~[hibernate-types-52-2.16.1.jar:na]
	at com.vladmihalcea.hibernate.type.json.internal.AbstractJsonSqlTypeDescriptor$1.doExtract(AbstractJsonSqlTypeDescriptor.java:34) ~[hibernate-types-52-2.16.1.jar:na]
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47) ~[hibernate-core-5.4.33.jar:5.4.33]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257) ~[hibernate-core-5.4.33.jar:5.4.33]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253) ~[hibernate-core-5.4.33.jar:5.4.33]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:249) ~[hibernate-core-5.4.33.jar:5.4.33]

Following are the entity class and query.
Entity:

@Entity
@Getter
@Setter
@NoArgsConstructor
@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
public class Party implements Serializable {
  @Id
  @GeneratedValue(generator = "uuid2")
  @GenericGenerator(name = "uuid2", strategy = "org.hibernate.id.UUIDGenerator")
  @Column(name = "PARTY_ID", columnDefinition = "VARCHAR(255)")
  private String partyId;

  @Type(type = "jsonb")
  @Column(columnDefinition = "jsonb")
  private PartyJsonObject partyJsonObject;
}
   
Query: 
 PartyJsonObject partyJsonObject =
        (PartyJsonObject)
            entityManager
                .createNativeQuery(
                    "select party_json_object from {h-schema}party where party_id = :partyId")
                .setParameter("partyId", partyId)
                .unwrap(NativeQuery.class)
                .addScalar("party_json_object", JsonBinaryType.INSTANCE)
                .getSingleResult();

Gradle Dependency:
    implementation group: 'com.vladmihalcea', name: 'hibernate-types-52', version: '2.16.1'

Please suggest.

**Comment by vladmihalcea** [comment]
The first thing you need to do is create a replicating test case using the existing tests in this repository. That will require you to get rid of Lonbok as well as it's not needed for this use case.

Second, you need to debug the problem and find what should be done for the issue to be fixed and send a Pull Request with the fix proposal.

Looking forward to your contribution.

**Comment by gauravgupta429** [comment]
Thanks for quick response.
Working fine now..
I have one more doubt.
If I am using following repository query
@Query(
      value = "select party_json_object from {h-schema}party where party_id = :partyId",
      nativeQuery = true)
  PartyJsonObject fetchPartyJSON(@Param("partyId") String partyId);

facing  below issue
java.lang.NullPointerException: null
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.setParameterValues(JsonTypeDescriptor.java:70) ~[hibernate-types-52-2.16.1.jar:na]
	at com.vladmihalcea.hibernate.type.json.JsonBinaryType.setParameterValues(JsonBinaryType.java:91) ~[hibernate-types-52-2.16.1.jar:na]
	at org.hibernate.type.TypeFactory.injectParameters(TypeFactory.java:123) ~[hibernate-core-5.4.33.jar:5.4.33]
	at org.hibernate.type.TypeFactory.type(TypeFactory.java:108) ~[hibernate-core-5.4.33.jar:5.4.33]

Please suggest

**Comment by vladmihalcea** [comment]
I can investigate a solution for that Spring Repository issue via consulting if you're interested.

**Comment by gauravgupta429** [comment]
Yes I am interested, This is one of my use-case.

**Comment by vladmihalcea** [comment]
Write me an email at vlad[at]vladmihalcea.com and I'll provide you more details.
