### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by Bulat3301** [vladmihalcea/hibernate-types#443]
Used java 17.
Pom:
```
<dependencies>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>4.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>4.0.0</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>6.0.1.Final</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.3.4</version>
        </dependency>
        <dependency>
            <groupId>com.vladmihalcea</groupId>
            <artifactId>hibernate-types-60</artifactId>
            <version>2.16.2</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>
    </dependencies>
```
Error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:138)
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:125)
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule.setupModule(JaxbAnnotationModule.java:98)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:853)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModules(ObjectMapper.java:1055)
	at com.fasterxml.jackson.databind.ObjectMapper.findAndRegisterModules(ObjectMapper.java:1139)
	at com.vladmihalcea.hibernate.type.util.ObjectMapperWrapper.<init>(ObjectMapperWrapper.java:32)
	at com.vladmihalcea.hibernate.type.util.ObjectMapperWrapper.<clinit>(ObjectMapperWrapper.java:24)
	at com.vladmihalcea.hibernate.type.util.Configuration.getObjectMapperWrapper(Configuration.java:158)
	at com.vladmihalcea.hibernate.type.json.JsonBinaryType.<init>(JsonBinaryType.java:36)
	at com.vladmihalcea.hibernate.type.json.JsonBinaryType.<clinit>(JsonBinaryType.java:30)
	at com.vladmihalcea.hibernate.type.HibernateTypesContributor.contribute(HibernateTypesContributor.java:54)
```

What did i do wrong?

**Comment by vladmihalcea** [comment]
My [High-Performance Java Persistence GitHub repository](https://github.com/vladmihalcea/high-performance-java-persistence) uses both Java 17 and Hibernate Types.

When running a test in debug, and inspecting the `XmlElement`, like this:

    XmlElement.class.getProtectionDomain().getCodeSource().getLocation().getPath(); 

This is what I get:

    /.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.jar

When running `mvn dependency:tree`, this is what I get:

```
+- com.vladmihalcea:hibernate-types-52:jar:2.16.2:compile
 |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.6:compile
 |     +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
 |     \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
```

So, the class should be resolved from there. I suppose you don't have to set anything. Most likely it's a different dependency you have that conflicts with this one.

You will have to run the same steps as I did to see where the `XmlElement` is loaded from.

**Comment by t0r0X** [comment]
Use Maven Enforcer Plugin, and then dependencies exclusion / pinning, in order to make sure there are no conflicting dependencies:
https://maven.apache.org/enforcer/maven-enforcer-plugin/
