### ISSUE TITLE
PGInterval can't be cast to PGInterval 

### ISSUE THREAD

**Issue by LokiMidgard** [vladmihalcea/hibernate-types#449]
Since I added this project as an dependency, I get the error `class org.postgresql.util.PGInterval cannot be cast to class org.postgresql.util.PGInterval`

One instance seems comes from the wildfly installation, the other from my deployed app.

The used version is `2.16.2`

<details>
<summary>Stacktrace</summary>

```
 Caused by: java.lang.ClassCastException: class org.postgresql.util.PGInterval cannot be cast to class org.postgresql.util.PGInterval (org.postgresql.util.PGInterval is in unnamed module of loader 'org.postgresql@42.2.19' @69679ba0; org.postgresql.util.PGInterval is in unnamed module of loader 'deployment.ris-idm-server-1.1.66-SNAPSHOT.war' @4e23c1bb)
   at deployment.ris-idm-server-1.1.66-SNAPSHOT.war//com.vladmihalcea.hibernate.type.interval.PostgreSQLIntervalType.get(PostgreSQLIntervalType.java:35)
   at deployment.ris-idm-server-1.1.66-SNAPSHOT.war//com.vladmihalcea.hibernate.type.interval.PostgreSQLIntervalType.get(PostgreSQLIntervalType.java:23)
   at deployment.ris-idm-server-1.1.66-SNAPSHOT.war//com.vladmihalcea.hibernate.type.ImmutableType.nullSafeGet(ImmutableType.java:98)
   at deployment.ris-idm-server-1.1.66-SNAPSHOT.war//com.vladmihalcea.hibernate.type.ImmutableType.hydrate(ImmutableType.java:290)
   at org.hibernate@5.3.9.Final//org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:3010)
   at org.hibernate@5.3.9.Final//org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1746)
   at org.hibernate@5.3.9.Final//org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1672)
   at org.hibernate@5.3.9.Final//org.hibernate.loader.Loader.getRow(Loader.java:1561)
   at org.hibernate@5.3.9.Final//org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:731)
   at org.hibernate@5.3.9.Final//org.hibernate.loader.Loader.processResultSet(Loader.java:990)
   at org.hibernate@5.3.9.Final//org.hibernate.loader.Loader.doQuery(Loader.java:948)
   at org.hibernate@5.3.9.Final//org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:340)
   at org.hibernate@5.3.9.Final//org.hibernate.loader.Loader.doList(Loader.java:2689)
   at org.hibernate@5.3.9.Final//org.hibernate.loader.Loader.doList(Loader.java:2672)
   at org.hibernate@5.3.9.Final//org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2506)
   at org.hibernate@5.3.9.Final//org.hibernate.loader.Loader.list(Loader.java:2501)
   at org.hibernate@5.3.9.Final//org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:504)
   at org.hibernate@5.3.9.Final//org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:395)
   at org.hibernate@5.3.9.Final//org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:220)
   at org.hibernate@5.3.9.Final//org.hibernate.internal.SessionImpl.list(SessionImpl.java:1507)
   at org.hibernate@5.3.9.Final//org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1537)
   at org.hibernate@5.3.9.Final//org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1505)
   at org.hibernate@5.3.9.Final//org.hibernate.query.Query.getResultList(Query.java:132)
   at deployment.ris-idm-server-1.1.66-SNAPSHOT.war//de.trier.fh.ris.dataaccess.services.PersonRoleServiceBean.getPersonRolesInfo(PersonRoleServiceBean.java:106)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   at org.jboss.as.ee@16.0.0.Final//org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
   at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
   at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
   at org.jboss.as.weld.common@16.0.0.Final//org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.delegateInterception(Jsr299BindingsInterceptor.java:79)
   at org.jboss.as.weld.common@16.0.0.Final//org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:89)
   at org.jboss.as.weld.common@16.0.0.Final//org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:102)
   at org.jboss.as.ee@16.0.0.Final//org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
   at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
   at org.jboss.as.ejb3@16.0.0.Final//org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
   at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
   at org.jboss.as.jpa@16.0.0.Final//org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
   at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
   at org.jboss.as.ee@16.0.0.Final//org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
   at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
   at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:40)
   at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
   at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
   at org.jboss.as.ee@16.0.0.Final//org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)
   at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
   at org.jboss.as.ejb3@16.0.0.Final//org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
   at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
   at org.jboss.as.ejb3@16.0.0.Final//org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54)
   at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
   at org.jboss.as.ejb3@16.0.0.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:185)
   ... 282 more
```

</details>

I use following types
```java
@TypeDef(name = "json", typeClass = JsonType.class)
@TypeDef(name = "date-array", typeClass = TimestampArrayType.class)
@TypeDef(name = "int-array", typeClass = IntArrayType.class)
@TypeDef(name = "long-array", typeClass = LongArrayType.class)
@TypeDef(name = "string-array", typeClass = StringArrayType.class)
@TypeDef(name = "bool-array", typeClass = BooleanArrayType.class)
@TypeDef(typeClass = com.vladmihalcea.hibernate.type.interval.PostgreSQLIntervalType.class, defaultForType = java.time.Duration.class)
```

I tried to set the problematic lib to provided, but then I got a class not found exception.

<details>
<summary>Stacktrace</summary>

```
 Caused by: java.lang.ClassNotFoundException: org.postgresql.util.PGInterval from [Module "deployment.ris-idm-server-1.1.66-SNAPSHOT.war" from Service Module Loader]
   at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
   at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
   at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
   at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
   ... 334 more
```
</details>

I probably have some missconfigurations, but I wasn't able to fix it. I would be happy someone could point me in the correct direction.

**Comment by vladmihalcea** [comment]
Most likely, that's a Java `ClassLoader` issue caused by Wildfly module system. Since this is beyond the scope of this project, I'm going to close this issue. You should use the Wildfly forums or RedHat support for this problem as they know better how to get it solved. Last time I used JBoss was in 2008, so I can't help you with that.

**Comment by LokiMidgard** [comment]
thank you for the direction.
