### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by JasonRui** [vladmihalcea/hibernate-types#45]
Hi, I have DTO have the field
`
@Type(type = "string-array")

@Column(columnDefinition = "text[]")

private List<String> tagIds = new ArrayList<>();
`

When I `session.saveOrUpdate(faqSource);`,

I got Exceptions:
18:35:50.806 ERROR c.w.c.f.w.s.e.ServiceExceptionResolver [COMPANY] java.util.ArrayList cannot be cast to [Ljava.lang.Object;
java.lang.ClassCastException: java.util.ArrayList cannot be cast to [Ljava.lang.Object;
	at com.vladmihalcea.hibernate.type.array.internal.ArrayUtil.deepCopy(ArrayUtil.java:38) ~[hibernate-types-43-2.3.0.jar:na]
	at com.vladmihalcea.hibernate.type.array.internal.AbstractArrayTypeDescriptor$1.deepCopyNotNull(AbstractArrayTypeDescriptor.java:26) ~[hibernate-types-43-2.3.0.jar:na]
	at org.hibernate.type.descriptor.java.MutableMutabilityPlan.deepCopy(MutableMutabilityPlan.java:52) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.type.AbstractStandardBasicType.deepCopy(AbstractStandardBasicType.java:321) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.type.AbstractStandardBasicType.deepCopy(AbstractStandardBasicType.java:317) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.type.TypeHelper.deepCopy(TypeHelper.java:67) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:281) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:195) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:138) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:209) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:194) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:114) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:684) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:676) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:671) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]`
`

need your help

**Comment by vladmihalcea** [comment]
You can find [a unit test that works like a charm](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-43/src/test/java/com/vladmihalcea/hibernate/type/array/ArrayTypeTest.java), so just compare my test to your and see the difference.
