### ISSUE TITLE
It throws "Could not instantiate Type: com.vladmihalcea.hibernate.type.array.ListArrayType" 

### ISSUE THREAD

**Issue by ParkJong-ic** [vladmihalcea/hibernate-types#500]
Haven't been able to solve it for 2 days. please.

I wrote a List<Point> in Spring to use polygon in Postgresql, but it doesn't work.

I basically followed the tutorial here https://vladmihalcea.com/postgresql-array-java-list/

my entity declaration is as below:

```
@Entity
@Getter
@TypeDef(name = "list-array", typeClass = ListArrayType.class)
@NoArgsConstructor
public class AdministrativeArea {

    @Id
    @Column(name = "administrative_area_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long administrativeAreaId;

    @Column(name = "administrative_area_name")
    private String name;

    @Type(type = "list-array")
    @Column(name = "administrative_area_area", columnDefinition = "integer[]")
    private List<Polygon> area;
```

got this error:

```
2022-10-19 15:25:09.527 ERROR 28796 --- [           main] j.LocalContainerEntityManagerFactoryBean : Failed to initialize JPA EntityManagerFactory: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.MappingException: Could not instantiate Type: com.vladmihalcea.hibernate.type.array.ListArrayType
2022-10-19 15:25:09.528  WARN 28796 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.MappingException: Could not instantiate Type: com.vladmihalcea.hibernate.type.array.ListArrayType
2022-10-19 15:25:09.528  INFO 28796 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-10-19 15:25:09.585  INFO 28796 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2022-10-19 15:25:09.586  INFO 28796 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-10-19 15:25:09.594  INFO 28796 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-10-19 15:25:09.615 ERROR 28796 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.MappingException: Could not instantiate Type: com.vladmihalcea.hibernate.type.array.ListArrayType
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.4.jar:2.7.4]
	at com.example.sia.project.ProjectApplication.main(ProjectApplication.java:10) ~[main/:na]
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.MappingException: Could not instantiate Type: com.vladmihalcea.hibernate.type.array.ListArrayType
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:421) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.23.jar:5.3.23]
	... 16 common frames omitted
Caused by: org.hibernate.MappingException: Could not instantiate Type: com.vladmihalcea.hibernate.type.array.ListArrayType
	at org.hibernate.type.TypeFactory.type(TypeFactory.java:114) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.type.TypeFactory.byClass(TypeFactory.java:71) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.type.TypeResolver.heuristicType(TypeResolver.java:126) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:500) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:482) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.mapping.Property.isValid(Property.java:231) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:627) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.mapping.RootClass.validate(RootClass.java:267) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:359) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:314) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:471) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1498) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[spring-orm-5.3.23.jar:5.3.23]
	... 20 common frames omitted
Caused by: java.lang.UnsupportedOperationException: The class java.awt.Point is not supported yet!
	at com.vladmihalcea.hibernate.type.array.internal.ListArrayTypeDescriptor.setParameterValues(ListArrayTypeDescriptor.java:145) ~[hibernate-types-52-2.20.0.jar:na]
	at com.vladmihalcea.hibernate.type.array.ListArrayType.setParameterValues(ListArrayType.java:39) ~[hibernate-types-52-2.20.0.jar:na]
	at org.hibernate.type.TypeFactory.injectParameters(TypeFactory.java:127) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.type.TypeFactory.type(TypeFactory.java:109) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	... 34 common frames omitted
```

**Comment by vladmihalcea** [comment]
The problem comes from this line:

`com.vladmihalcea.hibernate.type.array.internal.ListArrayTypeDescriptor.setParameterValues(ListArrayTypeDescriptor.java:145) ~[hibernate-types-52-2.20.0.jar:na]
`

And, if you [go there](https://github.com/vladmihalcea/hibernate-types/blob/d11ad935de8b05d9aedcb7953700f10f28d991e2/hibernate-types-55/src/main/java/com/vladmihalcea/hibernate/type/array/internal/ListArrayTypeDescriptor.java#L117), you'll see this:

```
sqlArrayType = parameters.getProperty(AbstractArrayType.SQL_ARRAY_TYPE);
if (sqlArrayType == null) {
	if (Integer.class.isAssignableFrom(arrayElementClass)) {
		sqlArrayType = "integer";
	} else if (Long.class.isAssignableFrom(arrayElementClass)) {
		sqlArrayType = "bigint";
	} else if (Double.class.isAssignableFrom(arrayElementClass)) {
		sqlArrayType = "float8";
	} else if (String.class.isAssignableFrom(arrayElementClass)) {
		sqlArrayType = "text";
	} else if (UUID.class.isAssignableFrom(arrayElementClass)) {
		sqlArrayType = "uuid";
	} else if (Date.class.isAssignableFrom(arrayElementClass) || LocalDateTime.class.isAssignableFrom(arrayElementClass)) {
		sqlArrayType = "timestamp";
	} else if (Boolean.class.isAssignableFrom(arrayElementClass)) {
		sqlArrayType = "boolean";
	} else if (BigDecimal.class.isAssignableFrom(arrayElementClass)) {
		sqlArrayType = "decimal";
	} else if (LocalDate.class.isAssignableFrom(arrayElementClass)) {
		sqlArrayType = "date";
	} else {
		throw new UnsupportedOperationException("The " + arrayElementClass + " is not supported yet!");
	}
}
```

So, you need to provide the `AbstractArrayType.SQL_ARRAY_TYPE`:

```
@Type(
	type = "list-array",
	parameters = @org.hibernate.annotations.Parameter(
		name = "sql_array_type",
		value = "polygon"
	)
)
@Column(name = "administrative_area_area", columnDefinition = "integer[]")
private List<Polygon> area;
```

Makes sense?

**Comment by ParkJong-ic** [comment]
I solved the problem. thank you
