### ISSUE TITLE
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonSerializer

### ISSUE THREAD

**Issue by nstdio** [vladmihalcea/hibernate-types#504]
If `hibernate-types` used in environment where `jackson-databind` is not on classpath the error is thrown:

```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonSerializer

	at com.vladmihalcea.hibernate.type.util.Configuration.getObjectMapperWrapper(Configuration.java:157)
	at com.vladmihalcea.hibernate.type.json.JsonType.<init>(JsonType.java:65)
	at com.vladmihalcea.hibernate.type.json.JsonType.<clinit>(JsonType.java:60)
	at com.vladmihalcea.hibernate.type.HibernateTypesContributor.contribute(HibernateTypesContributor.java:97)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:391)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:132)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:56)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54) <30 internal lines>
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JsonSerializer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 41 more
```

Because `Configuration` is linked with `ObjectMapper` class, it imports it.

**Comment by vladmihalcea** [comment]
@nstdio The JSON Types should be indeed only loaded when there is the Jackson library available.

**Comment by vladmihalcea** [comment]
Fixed.
