### ISSUE TITLE
Can we use @Type(type = "json") with @Formula?

### ISSUE THREAD

**Issue by hurelhuyag** [vladmihalcea/hibernate-types#509]
I'm experimenting new approach to fetch sub-collections. My first attempt is to use `group_concat`. It is working fine when the result type is a `string`.
```
    @Formula("(SELECT group_concat(cp.phone) FROM customerPhone cp WHERE cp.customer_id = id)")
    private String phonesArray;
```
But I'm trying to fetch a list of items. And my next attempt is to use `@Type(type = "json")` with `json_arrayagg`. Unfortunately, It is throwing NullPointerException.
```
    @Type(type = "json")
    @Formula("(SELECT json_arrayagg(cp.phone) FROM customerPhone cp WHERE cp.customer_id = id)")
    private List<String> phonesArray;
```

```
Caused by: java.lang.NullPointerException
	at java.base/java.lang.Class.isAssignableFrom(Native Method)
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.fromString(JsonTypeDescriptor.java:104)
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.wrap(JsonTypeDescriptor.java:165)
	at com.vladmihalcea.hibernate.type.json.internal.AbstractJsonSqlTypeDescriptor$1.doExtract(AbstractJsonSqlTypeDescriptor.java:34)
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257)
```
Is it possible? I think it is a really interesting approach to fetch sub-collections.

**Comment by vladmihalcea** [comment]
You can use `JsonType` for standard mappings or for queries.

Most likely, you could add support for `@Formula` if you need that. Try to debug the `NullPointerException` and see why it's thrown and what you should do to avoid getting it.

**Comment by hurelhuyag** [comment]
Turns out, My configuration is wrong. If I change like this. It is working.
```
@Type(type = "com.vladmihalcea.hibernate.type.json.JsonType")
```

**Comment by hurelhuyag** [comment]
Working with enums too. Thanks.

**Comment by vladmihalcea** [comment]
@hurelhuyag I'm glad you found the issue.
