### ISSUE TITLE
NPE with quarkus 3.0.0.Alpha5 and Hibernate 6

### ISSUE THREAD

**Issue by nyko29** [vladmihalcea/hibernate-types#592]

**Comment by nyko29** [comment]
When I launch my quarkus app in dev mode with the dependency 3.2.0 of hypersistence-utils, it fails during the startup with the following error 

```
2023-03-16 16:59:29,258 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-03-16 16:59:29,265 WARN  [io.qua.arc.impl] (Quarkus Main Thread) An error occurred during delivery of the @BeforeDestroyed(ApplicationScoped.class) event: jakarta.enterprise.inject.CreationException: Error creating synthetic bean [21527bfe81c05a31d9c61be490c9ebc04e8ab2d8]: jakarta.enterprise.inject.CreationException: Config root [io.quarkus.hibernate.orm.runtime.HibernateOrmRuntimeConfig] with config phase [RUN_TIME] not initialized yet.
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRuntimeConfig_21527bfe81c05a31d9c61be490c9ebc04e8ab2d8_Synthetic_Bean.doCreate(Unknown Source)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRuntimeConfig_21527bfe81c05a31d9c61be490c9ebc04e8ab2d8_Synthetic_Bean.create(Unknown Source)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRuntimeConfig_21527bfe81c05a31d9c61be490c9ebc04e8ab2d8_Synthetic_Bean.get(Unknown Source)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRuntimeConfig_21527bfe81c05a31d9c61be490c9ebc04e8ab2d8_Synthetic_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:48)
	at io.quarkus.hibernate.orm.runtime.JPAConfig_Bean.doCreate(Unknown Source)
	at io.quarkus.hibernate.orm.runtime.JPAConfig_Bean.create(Unknown Source)
	at io.quarkus.hibernate.orm.runtime.JPAConfig_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkus.hibernate.orm.runtime.JPAConfig_Observer_destroy_03fb872ecc5e4ea32f039e25a79f3b66499ca7ea.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:344)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:332)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:262)
	at io.quarkus.arc.impl.ArcContainerImpl.shutdown(ArcContainerImpl.java:389)
	at io.quarkus.arc.Arc.shutdown(Arc.java:58)
	at io.quarkus.arc.runtime.ArcRecorder$1.run(ArcRecorder.java:49)
	at io.quarkus.runtime.StartupContext.runAllInReverseOrder(StartupContext.java:84)
	at io.quarkus.runtime.StartupContext.close(StartupContext.java:73)
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: jakarta.enterprise.inject.CreationException: Config root [io.quarkus.hibernate.orm.runtime.HibernateOrmRuntimeConfig] with config phase [RUN_TIME] not initialized yet.
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRuntimeConfig_21527bfe81c05a31d9c61be490c9ebc04e8ab2d8_Synthetic_Bean.createSynthetic(Unknown Source)
	... 38 more


2023-03-16 16:59:29,266 DEBUG [io.qua.arc.impl] (Quarkus Main Thread) ArC DI container shut down
2023-03-16 16:59:29,267 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 14 more
Caused by: java.lang.NullPointerException
	at org.hibernate.type.spi.TypeConfiguration$Scope.getDialect(TypeConfiguration.java:459)
	at org.hibernate.type.EnumType$LocalJdbcTypeIndicators.getDialect(EnumType.java:515)
	at org.hibernate.type.descriptor.jdbc.VarcharJdbcType.shouldUseMaterializedLob(VarcharJdbcType.java:90)
	at org.hibernate.type.descriptor.jdbc.VarcharJdbcType.resolveIndicatedType(VarcharJdbcType.java:79)
	at org.hibernate.type.descriptor.java.BasicJavaType.getRecommendedJdbcType(BasicJavaType.java:33)
	at org.hibernate.type.descriptor.java.StringJavaType.getRecommendedJdbcType(StringJavaType.java:56)
	at org.hibernate.type.EnumType.configureUsingReader(EnumType.java:177)
	at org.hibernate.type.EnumType.setParameterValues(EnumType.java:139)
	at io.hypersistence.utils.hibernate.type.basic.PostgreSQLEnumType.setParameterValues(PostgreSQLEnumType.java:46)
	at org.hibernate.mapping.MappingHelper.injectParameters(MappingHelper.java:107)
	at org.hibernate.mapping.BasicValue.setExplicitCustomType(BasicValue.java:831)
	at org.hibernate.boot.model.internal.BasicValueBinder.fillSimpleValue(BasicValueBinder.java:1363)
	at org.hibernate.boot.model.internal.SetBasicValueTypeSecondPass.doSecondPass(SetBasicValueTypeSecondPass.java:27)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1846)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1792)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:324)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:407)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:101)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:73)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:40)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$1.created(HibernateOrmRecorder.java:78)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:75)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources844392269.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources844392269.deploy(Unknown Source)
	... 15 more


```

**Comment by vladmihalcea** [comment]
The Exception is thrown by Hibernate 
 
````
org.hibernate.type.spi.TypeConfiguration$Scope.getDialect(TypeConfiguration.java:459)
````

So, the problem is not with this library. Most likely it's due to how Quarkus bootstraps Hibernate, so you should open the issue on Quarkus.

**Comment by nyko29** [comment]
Ok thanks for your response. I post the issue there because without hypersistence-utils I don't have the problem. And you library seems to be the solution for the nightmare of enum managment with hibernate 6..

**Comment by nyko29** [comment]
I will switch to quarkus then

**Comment by vladmihalcea** [comment]
There are many integration tests using that Type in this project, so if there was a problem  it should have been detected even if you didn't use Quarkus.

Try it with a Spring Boot project and you'll see it working just fine.
