### ISSUE TITLE
 java.lang.ClassNotFoundException when ArrayList used

### ISSUE THREAD

**Issue by PaulSeiziger** [vladmihalcea/hibernate-types#85]
Hi, I have a problem with the ArrayList serialization in Jsonb format. I use PlayFramework. Did everything as stated in the article. 

Here are my entities:
```java
@Is1CSubentity
public class OutgoingBillPart implements Serializable {

    @JsonView(InReportView.class)
    @Field1C(key = "LineNumber")
    private int lineNumber;

    @JsonView(InReportView.class)
    @Field1C(key = "Содержание")
    private String target;

    @JsonView(InReportView.class)
    @Field1C(key = "Сумма")
    private BigDecimal amount;

    @Field1C(key="СуммаНДС")
    private BigDecimal amountTax;

    ....
}

@Is1CEntity(entityName = "Document_СчетНаОплатуПокупателю")
@Entity
@Table(name = "outgoing_bills")
public class OutgoingBill extends Abstract1CEntity implements ReconciliationDocument, IsEntity {
    @JsonView(InReportView.class)
    @Id
    @SequenceGenerator(name="outgoing_bills_id_seq",
            sequenceName="outgoing_bills_id_seq",
            allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "outgoing_bills_id_seq")
    private long id;

  	...

    @JsonView(InReportView.class)
    @Subentities1CFromTablePart(key = "Товары")
    @Type(type = "jsonb")
    @Column(columnDefinition = "jsonb")
    private List<OutgoingBillPart> parts;

    ...

}


@TypeDefs({
        @TypeDef(name = "string-array", typeClass = StringArrayType.class),
        @TypeDef(name = "int-array", typeClass = IntArrayType.class),
        @TypeDef(name = "json", typeClass = JsonStringType.class),
        @TypeDef(name = "jsonb", typeClass = JsonBinaryType.class),
        @TypeDef(name = "jsonb-node", typeClass = JsonNodeBinaryType.class),
        @TypeDef(name = "json-node", typeClass = JsonNodeStringType.class),
})
@MappedSuperclass
@EntityListeners(DefaultEntityChangeListener.class)
public abstract class Abstract1CEntity {
    @Guid1C
    protected UUID guid;

    @Gate1C
    @ManyToOne
    @JoinColumn(name = "gate_id", nullable = false)
    protected Gate1CDescription gate;

    @From1CSource
    @Transient
    protected transient boolean loadedFromSource;

    @Edited1C
    @Column(name = "is_edited", nullable = false, columnDefinition = "boolean default false")
    protected boolean isEdited = false;

    @SynchronizableWith1C
    @Column(name = "is_synchronizable", nullable = false, columnDefinition = "boolean default true")
    protected boolean isSynchronizable = true;

    ...
}
```

But when trying to serialize an ArrayList, it returns a ClassLoader null.
```java
public class ObjectMapperJsonSerializer implements JsonSerializer {

    private final ObjectMapperWrapper objectMapperWrapper;

    public ObjectMapperJsonSerializer (ObjectMapperWrapper objectMapperWrapper) {
        this.objectMapperWrapper = objectMapperWrapper;
    }

    @Override
    public <T> T clone (T value) {
        return (value instanceof Serializable)?
                (T) SerializationHelper.clone ((Serializable) value):
                objectMapperWrapper.fromString (
                    objectMapperWrapper.toString (value), (Class <T>) value.getClass ()
                );
    }
}

public final class SerializationHelper {
private static final CoreMessageLogger LOG = CoreLogging.messageLogger (SerializationHelper.class);

....

public static Object clone (Serializable object) throws SerializationException {
LOG.trace ("Starting clone through serialization");
if (object == null) {
return null;
}
return deserialize (serialize (object), object.getClass (). getClassLoader ());
}
....

```
And everything falls with an error:
```
ava.util.concurrent.ExecutionException: javax.persistence.PersistenceException: org.hibernate.type.SerializationException: could not serialize
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at integration_1c.gate_managers.DefaultEntity1CGateManager.decode(DefaultEntity1CGateManager.java:194)
	at integration_1c.gate_managers.DefaultEntity1CGateManager.decode(DefaultEntity1CGateManager.java:96)
	at integration_1c.gate_managers.DefaultEntity1CGateManager.loadEntities(DefaultEntity1CGateManager.java:53)
	at integration_1c.Downloader.lambda$null$0(Downloader.java:64)
	at integration_1c.Downloader.timelog(Downloader.java:93)
	at integration_1c.Downloader.lambda$execute$1(Downloader.java:49)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:142)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:100)
	at integration_1c.Downloader.execute(Downloader.java:48)
	at tasks.LoadDataFrom1CTask.lambda$null$0(LoadDataFrom1CTask.java:59)
	at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(LightArrayRevolverScheduler.scala:101)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.persistence.PersistenceException: org.hibernate.type.SerializationException: could not serialize
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1608)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1152)
	at integration_1c.persisters.Default1CPersister.lambda$put$0(Default1CPersister.java:49)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.hibernate.type.SerializationException: could not serialize
	at org.hibernate.internal.util.SerializationHelper.serialize(SerializationHelper.java:119)
	at org.hibernate.internal.util.SerializationHelper.serialize(SerializationHelper.java:144)
	at org.hibernate.internal.util.SerializationHelper.clone(SerializationHelper.java:75)
	at com.vladmihalcea.hibernate.type.util.ObjectMapperJsonSerializer.clone(ObjectMapperJsonSerializer.java:21)
	at com.vladmihalcea.hibernate.type.util.ObjectMapperWrapper.clone(ObjectMapperWrapper.java:73)
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor$2.deepCopyNotNull(JsonTypeDescriptor.java:39)
	at org.hibernate.type.descriptor.java.MutableMutabilityPlan.deepCopy(MutableMutabilityPlan.java:35)
	at org.hibernate.type.AbstractStandardBasicType.deepCopy(AbstractStandardBasicType.java:279)
	at org.hibernate.type.AbstractStandardBasicType.deepCopy(AbstractStandardBasicType.java:275)
	at org.hibernate.type.TypeHelper.deepCopy(TypeHelper.java:51)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:267)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)
	at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:67)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:189)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:132)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:58)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:778)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:751)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:756)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1146)
	... 7 more
Caused by: java.io.NotSerializableException: entities.OutgoingBillPart
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.ArrayList.writeObject(ArrayList.java:766)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.hibernate.internal.util.SerializationHelper.serialize(SerializationHelper.java:115)
	... 27 more
```
How can I avoid this problem?

**Comment by vladmihalcea** [comment]
`Caused by: java.io.NotSerializableException: entities.OutgoingBillPart`

The `OutgoingBillPart` conatins some properties that don't implement `Serializable`. Try to debug it and see why it generates the problem.

Also, if you find a problem, you need to provide a replicating test case and a fix. I'll take a look at it once you are done with your Pull Request.

**Comment by PaulSeiziger** [comment]
I do not think that I can provide a replicatable test, because The problem seems to be in the interaction of the library and my framework. Since playframework uses its own ClassLoader, and SerializationHelper requests the classloader from ArrayList and gets null (https://www.baeldung.com/java-classloaders). In the two fallback classloaders, there are classes from my libraries, but not my project.

Therefore, I would like to understand whether it is possible to somehow specify the correct classloader for SerializationHelper or dont use SerializationHelper and how to do it?

**Comment by vladmihalcea** [comment]
Yes, you can provide a replicating test case that shows the issue. You don't have to use the same stack you are using in your application. Just make sure you provide the same context. For instance, you can provide a custom ClassLoader during the test which provides the context that triggers the issue.

More, you could change the `ObjectMapperJsonSerializer` so that it uses this:

```
objectMapperWrapper.fromString(
     objectMapperWrapper.toString(value), (Class<T>) value.getClass()
)
```

when you supply a certain configuration option, like `Configuration.PropertyKey.ENABLE_JAVA_SERIALIZATION` to `false`.

As a workaround, you could just supply your own `PropertyKey.JSON_SERIALIZER` to do that as well.

**Comment by vladmihalcea** [comment]
Closed because no replicating test case was sent.
