### ISSUE TITLE
Problem with pattern in tstzrange

### ISSUE THREAD

**Issue by calvequi** [vladmihalcea/hibernate-types#89]
Hi @vladmihalcea, I am having an issue when timestamp values (in tstzrange columns) only have 4 digits for nanoseconds. My entity has a Range<ZonedDateTime> property mapped to tstzrange column:

`
@MappedSuperclass
@SuperBuilder(toBuilder = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Setter(value = AccessLevel.PACKAGE)
@Getter
@EqualsAndHashCode(of = "uuid")
@TypeDef(
    typeClass = PostgreSQLRangeType.class,
    defaultForType = Range.class
)
public class BaseEntity implements Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(generator = "UUID")
	@GenericGenerator(
		name = "UUID",
		strategy = "org.hibernate.id.UUIDGenerator"
	)
    private UUID uuid;
	
	@Column(name="row_status")
	private String rowStatus;
	
	@Column(name="last_modified_by")
	private String lastModifiedBy;
	
	@Column(
	    name = "sys_period",
	    columnDefinition = "tstzrange"
	)
    private Range<ZonedDateTime> sysPeriod;
}
`
When I update an existing row (with only 4 nanoseconds digits) I got this exception:

`
java.time.format.DateTimeParseException: Text '2019-03-27 16:33:10.2146-06' could not be parsed at index 10
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949) ~[na:1.8.0_131]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851) ~[na:1.8.0_131]
	at java.time.ZonedDateTime.parse(ZonedDateTime.java:597) ~[na:1.8.0_131]
	at java.time.ZonedDateTime.parse(ZonedDateTime.java:582) ~[na:1.8.0_131]
	at com.vladmihalcea.hibernate.type.range.Range.lambda$parseZonedDateTime$1(Range.java:438) ~[hibernate-types-52-2.4.2.jar:na]
	at java.util.function.Function.lambda$compose$0(Function.java:68) ~[na:1.8.0_131]
	at com.vladmihalcea.hibernate.type.range.Range.ofString(Range.java:259) ~[hibernate-types-52-2.4.2.jar:na]
	at com.vladmihalcea.hibernate.type.range.Range.zonedDateTimeRange(Range.java:399) ~[hibernate-types-52-2.4.2.jar:na]
	at com.vladmihalcea.hibernate.type.range.PostgreSQLRangeType.get(PostgreSQLRangeType.java:64) ~[hibernate-types-52-2.4.2.jar:na]
	at com.vladmihalcea.hibernate.type.range.PostgreSQLRangeType.get(PostgreSQLRangeType.java:37) ~[hibernate-types-52-2.4.2.jar:na]
	at com.vladmihalcea.hibernate.type.ImmutableType.nullSafeGet(ImmutableType.java:27) ~[hibernate-types-52-2.4.2.jar:na]
	at org.hibernate.type.CustomType.nullSafeGet(CustomType.java:119) ~[hibernate-core-5.4.2.Final.jar:5.4.2.Final]
`

**Comment by vladmihalcea** [comment]
You need to add the replicating test case and the fix as well. I'll take a look at it once you are done.

**Comment by vladmihalcea** [comment]
Closed because no replicating test case was sent.

**Comment by vladmihalcea** [comment]
Released in 2.4.3.
